### ISSUE TITLE
What should our primary branch name be?

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#1122]
# Description

It sounds like `main` may be the most common replacement for `master` (see https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx and https://twitter.com/Una/status/1271180494944829441) but we can also use our own standard (also see https://github.com/git-for-windows/git/issues/2674#issuecomment-641182890). What do others prefer for the client repo? Here are some suggestions:

* `main` and if our release process changes, we can add a `develop` branch and treat `main` as our stable branch
* `develop` and if our release process changes, we can add a stable branch called `main` or `stable` or something else

Personally, I prefer switching to `develop` as we continue rapid development during our pilot and tagging releases, but I'd like to hear what others think.

**Comment by eloquence** [comment]
+1 for `develop`, consistent with longstanding SD Cor practice. These repos have production releases associated with them, so using a branch name that clearly connotes that it may include unreleased changes makes sense to me.

**Comment by emkll** [comment]
+1 for the first suggestion:
> main and if our release process changes, we can add a develop branch and treat main as our stable branch

This would make this consistent with other repos (other than SecureDrop core) and GitHub default.

If ever we need a long running release branch for this project, and need to issue a point release containing only certain commits  from `main`, we can introduce a `develop` branch then.

**Comment by eloquence** [comment]
> If ever we need a long running release branch for this project

That sounds good to me as a rule of thumb to distinguish whether or not to introduce a `develop` branch to a repo. :) @creviera How do you feel about `main` for now?

**Comment by creviera** [comment]
I actually really appreciate your explanation above for using the branch name `develop`:

> These repos have production releases associated with them, so using a branch name that clearly connotes that it may include unreleased changes makes sense to me.

**Comment by eloquence** [comment]
I think the counterargument is that `main` is becoming the convention across GitHub, so if I'm a developer new to a repo and there's only ever a single branch where all the development work happens, that's where I expect to find things. Having a signed release tag that only exists on a branch called `develop` could be confusing in its own right ("did you mean to release directly from the `develop` branch?").

Hence the proposed pattern "once we introduce the regular use of release branches to a repo, we should clearly distinguish between development & release versions by having one branch called `develop`; until then, let's go with `main` as the default branch".

(I don't have a strong preference between those options, just trying to recap the pros and cons.)

**Comment by creviera** [comment]
since there isn't much feedback here from the team, let's go ahead and copy the infrastructure repo process: https://github.com/freedomofpress/infrastructure/issues/2696#issuecomment-652063005

it also sounds like others agree on eventually creating a `main` branch for https://github.com/freedomofpress/securedrop

**Comment by conorsch** [comment]
Thanks for pushing on this, @creviera! Since the infra repo isn't public, briefly: 1) create main branch, 2) start using it. I'm also in favor of "main" as a general default for the simpler repos. The points discussed above about "develop" being useful for more complex repos is a great one, and I look forward to following up. On a few of the web repos, @maeve-fpf & @harrislapiroff were discussing "staging" and "production" branches. So whatever non-master option works best for a given repo, we'll go with that. 

Let's all of us keep our eyes peeled for places where "master" is either hardcoded, or implicitly assumed. CI nightly builds is a top candidate, and possibly a few places scattered around in documentation, as well.

**Comment by creviera** [comment]
`git push master:main` will creates a new branch pointing to the same commit

**Comment by emkll** [comment]
Thanks @creviera , I've updated the default branch and opened a PR to update the references you've identified above, see https://github.com/freedomofpress/securedrop-client/pull/1126. We can always update our branching strategy in the future, if we feel the need to.

There are occurrences (alembic and mimeapps) that I think cannot be changed because they reference upstream components.

**Comment by maeve-fpf** [comment]
Suggestion here: I don't think I've seen this much in the wild, but github.com urls support saying `HEAD` instead of a branch name (or tag, commit, etc) for the ref: https://github.com/freedomofpress/securedrop-client/blob/HEAD/files/usr.bin.securedrop-client

I'm on a quest to advocate for never hardcoding a default branch, so, I recommend this as the fix!
