### ISSUE TITLE
Synchronize user data via /users endpoint

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#1157]
Once https://github.com/freedomofpress/securedrop-sdk/issues/131 is merged and an updated SDK is released, we can use the new `/users` endpoint added in SecureDrop 1.6.0 to keep the client's user DB in sync (as part of a regular sync), instead of relying on other information, such as the attribution of replies, to infer that a user should be added to or removed from the client database. This should also help to resolve #1143.

**Comment by eloquence** [comment]
We don't expect to resolve yet during the 10/28-11/12 sprint, but will do an initial technical investigation & scoping (1-2 hours max).

**Comment by eloquence** [comment]
Given the number of areas of the code where this is relevant (replies, seen data, login badge), this is not a small issue, so during the 11/12-11/25 @creviera and I will focus on finalizing scope and test plan/acceptance criteria.

**Comment by creviera** [comment]
I think this issue should be addressed in this order: https://github.com/freedomofpress/securedrop-client/issues/1143#issuecomment-742043843

**Comment by creviera** [comment]
I edited https://github.com/freedomofpress/securedrop-client/issues/1143#issuecomment-742043843 by adding step 0 to the order of operations, which gets us half way there towards user sync. Once we resolve user deletion issues server side we entirely resolve this issue (in step 5). 

The benefit to getting half-way there with syncing on user creation is that we can begin implementing the seen-by feature at the per-message level. Currently we're blocked on working on this feature because we reply on the replies sync to create users, and not all users have sent a reply.

So to get half-way there on synchronizing user data, we need to:

* Remove the current code that creates users from the replies sync
* Add a /users sync at the beginning of the MetadataSyncJob, which should also ensure that a "deleted" user is account is created, whether or not a user has ever been deleted, ensuring no error when later syncing replies with the "deleted" UUID association
