### ISSUE TITLE
Starting a server with new set of users while still logged in crashes client

### ISSUE THREAD

**Issue by gonzalo-bulnes** [freedomofpress/securedrop-client#1404]
## Description

_I am not sure this would happen in production, but I noticed it in development._

After the server connection is lost, the client crashes when the connection is re-established.

## Steps to Reproduce

1. Start a development server: `make dev`
2. Start the client: `LOGLEVEL=debug ./run.sh --sdc-home ~/.securedrop-client`
3. Wait for a sync to finish.
4. Stop the server.
5. Wait for the client to print the banner: "The SecureDrop server cannot be reached. Trying to reconnect..."
6. Start the server.
7. Observe the client crashing. A traceback (see below) is printed to STDOUT.

## Expected Behavior

The client re-connects to the server, the banner is hidden and sync's resume.

## Actual Behavior

The client crashed with the following error:

```
Traceback (most recent call last):
  File "/home/user/src/securedrop-client/securedrop_client/logic.py", line 646, in on_sync_success
    self.authenticated_user.username != self.api.username
  File "/home/user/src/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 276, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/user/src/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 677, in get
    value = state._load_expired(state, passive)
  File "/home/user/src/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 660, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/home/user/src/securedrop-client/.venv/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 985, in load_scalar_attributes
    raise orm_exc.ObjectDeletedError(state)
sqlalchemy.orm.exc.ObjectDeletedError: Instance '<User at 0x707f54d0c048>' has been deleted, or its row is otherwise not present.
```

## Comments

A `git bisect` took me to (74d0eb001e3583f7b6cc702c5ed12021f0e20227):

```
74d0eb001e3583f7b6cc702c5ed12021f0e20227 is the first bad commit
commit 74d0eb001e3583f7b6cc702c5ed12021f0e20227
Author: Allie Crevier <allie@freedom.press>
Date:   Tue Jan 18 21:48:23 2022 -0800

    sync users with server before working with replies
    
    Signed-off-by: Allie Crevier <allie@freedom.press>

:040000 040000 4748a6d9a9fa7ba108a67a767962b46b714b62e5 7ed89f8b953383c5f77a87294f25ce970ed6deaa M	securedrop_client
:040000 040000 d59a3341661d2ab2c9f31b614871c8b5a95f7adc f189eef2d9d4e9405ba4614c65163cda73a8f8ba M	tests
```

The commit seems relevant given the error message. @creviera happy to :pear: troubleshooting further!

**Comment by creviera** [comment]
@gonzalo-bulnes this looks related to https://github.com/freedomofpress/securedrop-client/pull/1397

**Comment by creviera** [comment]
I was able to repro, and now understand that the issue has to do with the user being deleted while logged in when you destroy the dev server and start it with a whole new set of users.

I also tested (to double-check) that when you properly delete a user who is currently logged in, that the user is immediately logged out with the `Your session expired. Please log in again.` message.

The way this STR tests deleting the currently-authenticated user here is pretty unconventional, since you're deleting the user via a dev script that creates a new dev server when you start a new Docker container, but we shouldn't crash in any case, so I'll create a patch! Thanks for reporting!

**Comment by creviera** [comment]
I was able to repro, and now understand that the issue has to do with the user being deleted while logged in when you destroy the dev server and start it with a whole new set of users.

I also tested (to double-check) that when you properly delete a user who is currently logged in, that the user is immediately logged out with the `Your session expired. Please log in again.` message.

The way this STR tests deleting the currently-authenticated user here is pretty unconventional, since you're deleting the user via a dev script that creates a new dev server when you start a new Docker container, but we shouldn't crash in any case, so I'll create a patch. Thanks for reporting!

**Comment by conorsch** [comment]
Thanks for the clear report, @gonzalo-bulnes. The edge case seems very specific to the way we test in a dev environment. Given that the regression was introduced as part of recent changes, makes sense to fix. I'm happy to take on review of #1407, and then I'll work on bumping to rc2 after it's in.

**Comment by creviera** [comment]
# Staging STR

I was unable to create an STR that demonstrates the same dev behavior where the client crashes, but we can confirm that the client logs the user out when the user is deleted from the server in an "unconventional way". The following steps are copied from the QA Test Plan here: https://github.com/freedomofpress/securedrop-client/issues/1402#issue-1114522606 using a staging server:

* Create a user with username = "deleteme"
* Log into the client as the user
* Stop the tor service on the server that the client is connected to
* Delete the user in the server database
* Start the tor service and wait until the client auto reconnects
- [ ] Confirm that the "deleteme" user is logged out once the client can re-establish a connection to the server
