### ISSUE TITLE
[0.6.0rc3 QA] File not deleted from disk until next sync

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#1422]
## Description

When deleting sources or conversations, the UI indicates fast completion of the action, but the file is not actually removed from disk until the next sync.

This means that if you exit the app before then, the file remains on disk, and will only be removed on the next sync (the source or conversation will briefly re-appear on app start).

## Steps to Reproduce

1. On `sd-app`, monitor the contents of the `~/.securedrop_client/data` directory, e.g., via `watch -n 1 ~/.securedrop_client/data` in a terminal.
2. Create a new source and upload a file
3. Log into the client, wait for it to sync, and download the file
4. Wait for the next sync to finish by observing the sync animation or monitoring logs
5. Delete the source or conversation
6. After the deletion operation visually completes, wait a few seconds, but not until the next sync
7. Exit the app

## Expected Behavior

The file is removed from `sd-app` pretty much immediately after the app shows that the deletion operation is complete

## Actual Behavior

The file is still present in `sd-app` (even though the client log shows "successfully deleted at server")

## Comments

I don't know if this was an intentional trade-off decision during implementation of #1386, but I am logging it as surprising and potentially problematic given the "files remain on disk when the user does not expect it" outcome. I would expect the app to delete the files when it says that it has done so, not when the app syncs with the server again.

This does appear to be a change in behavior compared with 0.5.1:
- In 0.5.1, conversation deletion kicks off a sync after the UI is updated, which means that the time window for a file to continue to exist on disk is shorter.
- In 0.5.1, source deletion is painfully slow, but indicates that it is in progress until the file is actually deleted from disk.

**Comment by rocodes** [comment]
As far as I can tell, this is sort-of expected (although maybe not desirable!) behaviour that goes back to March 2020.

- At that time, we moved from [local delete to sync-to-delete](https://github.com/freedomofpress/securedrop-client/commit/a46ecdb84c1116d4b5ddaa6444c454b26c50b358#diff-bd9c8ec560911b1924ac2bee334a948c32c82130491940b48a5dd2c38ec8110fL750), and made it explicit in our tests that [local delete was a regression](https://github.com/freedomofpress/securedrop-client/commit/8c8572725b5e813238ea41a75ddb79cba3f503c5#diff-1b69200ebf60e8c9e1fc9c45a1ab746d4183dead9c1c9509169582841ab89d6eL1304-R1304)
- Then when we moved away from force-syncing, the "local delete doesn't happen" behaviour was still present.

I'm hesitant to make any big changes without Allie here, but I'm going to play around with what happens if we local-delete and then sync.

**Comment by eloquence** [comment]
Thanks @rocodes, after sleeping on it, my sense is that it makes sense to further discuss the desirable behavior as a team and potentially iterate on it. IMO the client should delete from disk the moment the server responds "I've deleted this", but I understand that there are reasons we've been cautious about this, e.g., with the risk of stale sync data (from a previous API request that responds late) potentially reinstating information.

We can discuss this more in our release go/no-go call, but I don't think this is a blocker for the current release.

**Comment by eloquence** [comment]
Recap of release check-in today: We'll proceed with 0.6.0 on Monday without a fix for this issue, but will focus on a subsequent point release to address.
