### ISSUE TITLE
Disable "download all files" after files have been deleted

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#1442]
## STR

1. Select a source with files that have not yet been downloaded
2. Delete the source conversation
3. Select the source menu

## Expected

The "download all files" option to be disabled, since there are no longer files to download.

## Actual

The "download all files" option is enabled, and if you select it then you get an error message in the status bar that the file could not be downloaded.

**Comment by creviera** [comment]
@gonzalo-bulnes this is a followup issue for https://github.com/freedomofpress/securedrop-client/pull/1388

**Comment by gonzalo-bulnes** [comment]
For coordination: I'm looking into it.

**Comment by gonzalo-bulnes** [comment]
Action plan:
- Ensure the interface of `state.State` contains a method to remove conversation files (by `ConversationId` to remove all the files at once I think, to be confirmed. We can make it file by file too.)
- Refactor the `DeleteConversationAction` so that the actions interacts with the controller, and not the confirmation dialog (because that's harder to read and test). To that purpose, I've drafted a refresh of #1375 (I'll open a new PR and close that one instead of updating it - [work in progress](https://github.com/freedomofpress/securedrop-client/compare/main...gonzalo-bulnes:refactor-remove-controller-dependency-from-dialogs-2?expand=1), a few action tests are missing).
- In the trigger part of `DeleteConversationAction`, add a command to update the state instance. With the refactoring above, this fix should be a one-liner, and should be enough to ensure that the `DownloadConversation` action is disabled when the conversation is deleted.

:eyeglasses: **Longer term vision**: this continues establishing a pattern where the updates of `state.State` that are caused by user actions will be triggered from the _actions_. Those are tiggered along with the controller commands for now, until we trigger the controller commands automatically when the state changes.
