### ISSUE TITLE
`update_replies()`: purge or mark stale pending ("draft") replies

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-client#1493]
If #1486 is merged, a new state arises in which it's possible that:

> 1. we have draft replies still marked as pending from a *previous* Client invocation;
> 2. we have no `SendReplyJob`s pending in the queue in *this* Client invocation; and
> 3. these replies are not present in the set of replies returned by the Server.

We already handle the cases in which:

1. [draft replies have been confirmed by the Server](https://github.com/freedomofpress/securedrop-client/blob/5349519f25a3b63a198bf2e8d94128f4b25e9bef/securedrop_client/storage.py#L666-L684); and
2. [local replies have been deleted on the Server](https://github.com/freedomofpress/securedrop-client/blob/5349519f25a3b63a198bf2e8d94128f4b25e9bef/securedrop_client/storage.py#L686-L699).

To this we need to add the case in which:

3. draft replies have *not* been confirmed by the Server but are no longer pending (because their `SendReplyJob`s do not persist from a previous Client invocation, per #410), are therefore stale, and should be either purged or marked failed.

_Originally posted by @cfm in https://github.com/freedomofpress/securedrop-client/issues/1486#issuecomment-1130834817_

**Comment by cfm** [comment]
This triangle of cases, in which the Client has a set of confirmed replies X and the Server has a set of confirmed replies Y, strongly suggests to me that the `DraftReply` object and table should be merged into `Reply`, with each `Reply`'s status reconciled by a single function over X and Y.  I actually think that refactoring will be _simpler_ even to implement—not only to reason about!—than just adding (3) above as a third case in `securedrop_client.storage.update_replies()`.

**Comment by gonzalo-bulnes** [comment]
My thoughts:

From a UI perspective, I much prefer the option of making those stale (Draft)Replies as `failed` rather than deleting them.
The replies are (and should keep being) rendered optimistically in the conversation timeline. That's immediate feedback that the journalist intent to send the reply was recorded.

If we mark (Draft)Replies as `failed`, we can use that information to indicate that a message was actually not sent. At that point, we could even offer the journalist an option to **retry** sending the message.  (iMessage for sure does that, maybe Signal too?)

**Comment by zenmonkeykstop** [comment]
hah - as it happens I just set up the workstation for the first time in a while, and I managed to b0rk the setup such that downloading and decrypting messages worked but sending replies did not (typo in fingerprint in `config.json`) - and having a "failed-> why? -> retry" option would definitely have sped up resolution.

**Comment by rocodes** [comment]
The original intent was that draft replies should be preserved but marked as 'failed' if the client closed or the user's session ended before the draft was successfully sent to the server (for anyone following up, eg for the hackathon, see the section on pending and failed replies for a quick visual of how this should look: https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Acceptance-Tests#replies. We don't have saveable, editable "Drafts" the same way an email client would allow, but a message that hasn't yet reached the server is considered a draft and is currently stored in a separate table in our database).

I agree that being able to optionally retry sending of messages that have previously failed to send would be great. Either way though, I think that failed drafts should still be preserved in the conversation pane, clearly marked as "failed to send", whether or not we implement the retry feature. (Otherwise it's kind of misleading to journalists dealing with network connectivity issues--imagine "I could have sworn I pressed send on a reply, but now it's gone?!")

Combining the DraftReply and Reply tables makes sense to me on first blush, although I haven't thought a lot about it. (Again, for anyone looking to pick this up, see [the readme](https://github.com/freedomofpress/securedrop-client/blob/HEAD/README.md#generating-and-running-database-migrations) on alembic migrations or feel free to ask us for more information here.)

**Comment by cfm** [comment]
It turns out that this will now be addressed by #1486.  I'll open a follow-up ticket for the refactoring suggested in <https://github.com/freedomofpress/securedrop-client/issues/1493#issuecomment-1130898792>, on the assumption that the Journalist API v2 will require parity between the Client and Server data models.
