### ISSUE TITLE
Support granular error messaging when exporting conversations

### ISSUE THREAD

**Issue by gonzalo-bulnes** [freedomofpress/securedrop-client#1605]
## Description

Since https://github.com/freedomofpress/securedrop-export/pull/105, the `export.Service` receives granular error codes from `sd-devices`, but the GUI doesn't currently take advantage of that. E.g. If a USB drive with multiple partitions is inserted, `sd-devices` responds with `USB_ENCRYPTION_NOT_SUPPORTED` which suggests that the USB drive is not adequate. The GUI currently renders that code as `UNEXPECTED_RETURN_STATUS` which leaves journalists guessing what part of the process might have failed.

Closes https://github.com/freedomofpress/securedrop-export/issues/70

**Comment by rocodes** [comment]
Adding specific ways we can improve the "unexpected_return_status" message:

- Show a human-readable message and not the error status (i.e. map error statuses to more sensible error messages in the client).
- Take advantage of the more detailed export status values that sd-devices supports (when we switch to consuming the new export status values), and show different error messages depending where the process failed, so that the user can differentiate between "Export failed [and files are not on the usb drive]" and "Files are on the usb drive, but some later part of the export process [ie the cleanup]" has failed. (This is the new ERROR_EXPORT_CLEANUP status.)

(Ran into this issue because I was brosing my export device in Nautilus (in sd-devices) during export, and the cleanup method was unable to unmount the drive. I saw an "Export failed" message, though it's not technically true--export succeeded, the files were there, unmounting failed -- and this is something that will be resolved by using the new statuses reported by sd-devices).
