### ISSUE TITLE
Release securedrop-client 0.9.0

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-client#1637]
This issue tracks the SecureDrop Client release 0.9.0. It will be organized by:

- Release Manager: @zenmonkeykstop 
- Deputy Release Manager: @rocodes 

This release includes the following changes:
- adds support for printing and exporting conversation transcripts, and for exporting full conversations
- updates download time-outs to address Tor Network performance changes
- adds status bar showing information on sync progress.
- numerous bugfixes and improvements.

SecureDrop maintainers and testers: As you QA this release, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the release milestone for tracking (or ask a maintainer to do so).

## Test plan
Available [below](https://github.com/freedomofpress/securedrop-client/issues/1637#issuecomment-1468940421). Please post results as a comment to this issue.

- [ ] Pseudolocale (`LANG=en_XA`) QA per <https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Acceptance-Tests#internationalization-reference>

## Installing an RC in a production workstation:

- shut down `sd-app` if it's running
- download the securedrop testing key https://raw.githubusercontent.com/freedomofpress/securedrop/develop/securedrop/tests/files/test_journalist_key.sec in a networked VM 
- copy it to dom0 with "qvm-run --pass-io <VNName> `cat <keyfile>` > testkey.sec" (qrexec policies prevent direct `qvm-copy` to `sd-small-bullseye-template`)
- copy it to the small template with "qvm-copy-to-vm sd-small-bullseye-template testkey.sec"
- in a small template terminal: 
  - install the key with "cat QubesIncoming/dom0/testkey.sec | sudo apt-key add"
  - edit `/etc/apt/sources.list.d/securedrop_workstation.list`, changing `apt.freedom.press` to `apt-test.freedom.press`
  - run "sudo apt-get update"
  - run "sudo apt install --upgrade securedrop-client"
  - revert the apt config change to prevent any other packages from being updated from test repos
  - shutdown the small template
- start the client as normal via the desktop icon.

## Release tasks

- [x] Check if there are any security bug fixes waiting to be pulled into the RC
- [x] Check if there are any translations:
    - [x] pending merge into `main`
    - [x] pending inclusion as a supported language in [`MANIFEST.in`](https://github.com/freedomofpress/securedrop-client/blob/main/MANIFEST.in)
- [x] Update changelog
- [ ] Create test plan
- [x] Build RC package
- [x] Begin formal QA using RC; increment RC and rebuild as needed
- [x] Build production package in standard [build environment](https://github.com/freedomofpress/securedrop-builder/wiki/FAQ#how-do-i-create-a-local-environment-suitable-for-building-packages)
- [x] Sign production package
- [x] Perform final pre-flight testing using apt-qa.freedom.press
  - [ ] **Localization:** In a dispVM, change your locale (e.g.: `export LANG=es_ES.utf-8; dpkg-reconfigure locales`), run the Client, and confirm that the application is translated.
- [x] Publish production package
- [ ] Publicize release via support channels
- [ ] Close https://github.com/freedomofpress/securedrop-client/issues/1533

**Comment by eloquence** [comment]
The changes in https://github.com/freedomofpress/securedrop-builder/pull/402/files moved the `.desktop` file to a new location, which has also been updated in the `dom0` launcher [here](https://github.com/freedomofpress/securedrop-workstation/blob/main/launcher/sdw_updater_gui/UpdaterApp.py#L21). If we release the Client without the changes in the `dom0` launcher, the `dom0` desktop shortcut will fail to launch the SecureDrop Client. 

We either have to back out the rename for 0.9.0, or ship an RPM at the same time that includes the change. Even if we ship an RPM, we'd have to carefully think through the order of update operations to avoid first-run errors.

**Comment by zenmonkeykstop** [comment]
Looks like the workstation rpm with the change, 0.7.1, was staging-only to unbreak testing against nightlies.  It wasn't tagged and the commit wasn't recorded in the build log :cry: so we can't use it as is and would have to cut a  new one anyway. My vote would be to  back out the change for now.

**Comment by eaon** [comment]
I'd vote for releasing this with both the new `.desktop` and the old `.desktop` file (basically just reverting or not including #1601 in the release) cause then we can handle `securedrop-workstation` (and `securedrop-updater`) completely independently and not worry

**Comment by zenmonkeykstop** [comment]
RC2 installed and the icon thing is sorted. Test plan also coming together so I think we're pretty much go for QA. Will add some notes on switching to the RC version in a prod workstation.

**Comment by rocodes** [comment]
## Test Plan
**Instructions**: It is helpful to have real-world scenarios simulated in the test plan, so if you don't get through every single Export or Download scenario, that's fine. You are encouraged to creatively test the interactions between features (eg by prompting a download and then exporting, or interrupting network connectivity, etc).

You will need a LUKS-encrypted Transfer Device and/or an SDW compatible printer to complete the export or print testing portions.

### Test Environment
Use a modified prod setup as per parent comment.
Hardware: <FIXME write your hardware specs here>

### Testing

PR: https://github.com/freedomofpress/securedrop-client/pull/1639

- [ ] Clicking the SecureDrop icon on the desktop starts the Client

----

PR: https://github.com/freedomofpress/securedrop-client/pull/1531
PR: https://github.com/freedomofpress/securedrop-client/pull/1536

1. Start the client in Portuguese:
   ```bash
  user@sd-app: LANG=pt_PT securedrop-client
   ```
   - [ ] The Client loads in Portuguese (Portugal):
   - [ ] Dates displayed in the source list are localized
   - [ ] Date displayed at the top of the conversation is localized

- [ ] The Client loads in Chinese (Simplified):
  ```bash
  user@sd-app: LANG=zh_Hans securedrop-client
  ```

----

PR:
    - https://github.com/freedomofpress/securedrop-client/pull/1604
    - https://github.com/freedomofpress/securedrop-client/pull/1613
 
1. Seed the server with at least one source with a few dozen messages
2. Start the Client
   - [ ] Confirm that the message "Retrieveing N messages" is displayed when the files are being downloaded
 
----
 
 PR: 
    - https://github.com/freedomofpress/securedrop-client#1582
    - https://github.com/freedomofpress/securedrop-client#1621
    - https://github.com/freedomofpress/securedrop-client#1624
 
1. Choose to "Export Transcript"
   - [ ] Confirm that the transcript is exported, and contains all the messages
2. Send a reply
3. Choose to "Export Transcript" again
   - [ ] Confirm that the transcript that is exported includes the latest reply

----

PR: https://github.com/freedomofpress/securedrop-client/pull/1388

1. Choose to "Download All Files"
   - [ ] Confirm that all the files for that source are displayed as "downloading…"
   - [ ] Confirm that all files are eventually downloaded
   - [ ] Attempting "Download all" in offline mode flashes message that sign-in is required
   
----

PR:
    - https://github.com/freedomofpress/securedrop-client/pull/1627
Export All/Export Transcript
Assumptions for general QA of export features:
    - Export all and export transcript work in online and offline mode
    - Error-handling (e.g. for wrong USB passphrase) is the same as with existing export

1. Select a source which files are not all downloaded
2. Select "Export All Files and Transcript"
   - [ ] Confirm that a dialog indicates that not all files will be exported
   - [ ] Confirm that cancelling does that (nothing)
3. Select "Export All Files and Transcript" again
   - [ ] Confirm that the same dialog is displayed
   - [ ] Confirm that continuing does display the usual export dialog
   - [ ] Confirm that export dialog title is translated when exporting a single file ("Preparing to export:…") (PR: https://github.com/freedomofpress/securedrop-client/pull/1539)
   - [ ] Confirm that continuing does export the files that were dowloaded and the transcript
   - [ ] Confirm that the exported transcript includes the latest messages and replies

4. Download all the files
5. Select "Export All Files and Transcript" once more
   - [ ] Confirm that no confirmation dialog is displayed this time, only the regular export dialog
   - [ ] Confirm that cancelling does that (nothing)

6. Select "Export All Files and Transcript"
   - [ ] Confirm that no confirmation dialog is displayed this time, only the regular export dialog
   - [ ] Confirm that continuing does export the files that were dowloaded and the transcript
   - [ ] Confirm that the exported transcript includes the latest messages and replies

7. Select one file and export it:
   - [ ] Confirm that displays the usual export dialog
   - [ ] Confirm that export dialog title is translated when exporting a single file ("Preparing to export:…")

8. Upload a large file from a source
9. Select "Download All Files"...
10. ...and choose "Export All Files and Transcript" before the dowload finishes
   - [ ] Confirm that a dialog indicates that not all files will be exported
   - [ ] Confirm that continuing does display the usual export dialog
   - [ ] Confirm that export dialog title is translated when exporting a single file

----

1. Upload a few files of different sizes (3kB, 1MB, 10MB) as a source
    - [ ] Confirm that you can download them as a journalist over Tor

----

PR: https://github.com/freedomofpress/securedrop-client/pull/1486

1. Create a new source and submit a message.
2. Log into the Client and wait for sync.
3. Send a reply and wait for it to send.
4. Disconnect `sd-whonix` from `sys-firewall` or run `sudo service tor stop` in sd-whonix.
5. Send at least `n >= 1` more replies.
6. Quit the Client.
7. Reconnect `sd-whonix` to `sys-firewall` or `sudo service tor start` in sd-whonix.
11. Wait several seconds.
12. Start the Client again.
13. Log in again and wait for sync.
14. [ ] Observe only the first message from step (5) has succeeded...
15. [ ] ...and the rest are marked `Failed to send`.
16. Repeat steps (1)‒(15), but log out (and back in) rather than quitting and restarting the Client.
14. [ ] Observe only the first message from step (5) has succeeded...
15. [ ] ...and the rest are marked `Failed to send`.

**Comment by cfm** [comment]
With `securedrop-client` `0.9.0rc2+bullseye`, a few test-plan nits, but no testing concerns!


### Test Environment
- [x] Use a modified prod setup as per parent comment.

**Hardware**:
```
Qubes release 4.1.2 (R4.1)

Brand:        LENOVO
Model:        20W0CTO1WW
BIOS:        N34ET48W (1.48 )

Xen:        4.14.5
Kernel:        5.15.94-1

RAM:        48871 Mb

CPU:
  11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
Chipset:
  Intel Corporation 11th Gen Core Processor Host Bridge/DRAM Registers [8086:9a14] (rev 01)
VGA:
  Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])

Net:
  Intel Corporation Ethernet Connection (13) I219-V (rev 20)
  Intel Corporation Wi-Fi 6 AX210/AX211/AX411 160MHz (rev 1a)
```

### Testing

PR: https://github.com/freedomofpress/securedrop-client/pull/1639

- [x] Clicking the SecureDrop icon on the desktop starts the Client

**`securedrop-launcher.desktop` is not usable under i3,** but this worked nicely to start the `SecureDrop Workstation preflight updater` (I normally upgrade directly through Qubes Update):
    
```sh-session
[user@dom0 ~]$ $(cat ~/Desktop/securedrop-launcher.desktop | grep "^Exec=" | sed "s/Exec=//")
```

----

PR: https://github.com/freedomofpress/securedrop-client/pull/1531
PR: https://github.com/freedomofpress/securedrop-client/pull/1536

1. Start the client in Portuguese:

    ```bash
   user@sd-app: LANG=pt_PT securedrop-client
    ```
    - [x] The Client loads in Portuguese (Portugal)
    - [ ] Dates displayed in the source list are localized
    - [ ] Date displayed at the top of the conversation is localized

**No,** but that's [not what #1626 does *towards* #1536](https://github.com/freedomofpress/securedrop-client/pull/1626#pullrequestreview-1296469532).  Date time-zones *are* localized by #1626.

- [x] The Client loads in Chinese (Simplified):

   ```bash
   user@sd-app: LANG=zh_Hans securedrop-client
   ```

----

PR:
    - https://github.com/freedomofpress/securedrop-client/pull/1604
    - https://github.com/freedomofpress/securedrop-client/pull/1613
 
1. Seed the server with at least one source with a few dozen messages

```sh-session
sdadmin@app:~$ sudo -u www-data /var/www/securedrop/loaddata.py --source-count 2 --messages-per-source 12 --files-per-source 12 --replies-per-source 12
Created journalist (username=clarkkent, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=False)
Created source 1/2 (codename: 'cosmos margarita conform reaffirm untoasted promoter connected', journalist designation 'grass-covered meat', files: 12, messages: 12, replies: 12)
Created source 2/2 (codename: 'goatskin pouring upturned extrovert laptop bullish grudge', journalist designation 'omnivorous confession', files: 12, messages: 12, replies: 12)
```

3. Start the Client
   - [x] Confirm that the message "Retrieving N messages" is displayed when the files are being downloaded
 
----

PR: https://github.com/freedomofpress/securedrop-client/pull/1388

1. Choose to "Download All Files"
   - [x] Confirm that all the files for that source are displayed as "downloading…"
   - [x] Confirm that all files are eventually downloaded
   - [x] Attempting "Download all" in offline mode flashes message that sign-in is required
   
----

**Export All/Export Transcript Assumptions** (for general QA of export features):
    - Export all and export transcript work in online and offline mode
    - Error-handling (e.g. for wrong USB passphrase) is the same as with existing export

 PR: 
    - https://github.com/freedomofpress/securedrop-client/pull/1582
    - https://github.com/freedomofpress/securedrop-client/pull/1621
    - https://github.com/freedomofpress/securedrop-client/pull/1624
 
1. Choose to "Export Transcript"
   - [x] Confirm that the transcript is exported, and contains all the messages
2. Send a reply
4. Choose to "Export Transcript" again
   - [x] Confirm that the transcript that is exported includes the latest reply

PR:
    - https://github.com/freedomofpress/securedrop-client/pull/1627

1. Select a source which files are not all downloaded
2. Select "Export All Files and Transcript"
   - [x] Confirm that a dialog indicates that not all files will be exported
   - [x] Confirm that cancelling does that (nothing)

**NB.**  Visible menu item is `Export All`.

3. Select "Export All Files and Transcript" again
   - [x] Confirm that the same dialog is displayed
   - [x] Confirm that continuing does display the usual export dialog
   - [x] Confirm that export dialog title is translated when exporting a single file ("Preparing to export:…") (PR: https://github.com/freedomofpress/securedrop-client/pull/1539)
   - [x] Confirm that continuing does export the files that were dowloaded and the transcript
   - [x] Confirm that the exported transcript includes the latest messages and replies

5. Download all the files
6. Select "Export All Files and Transcript" once more
   - [x] Confirm that no confirmation dialog is displayed this time, only the regular export dialog
   - [x] Confirm that cancelling does that (nothing)

7. Select "Export All Files and Transcript"
   - [x] Confirm that no confirmation dialog is displayed this time, only the regular export dialog
   - [x] Confirm that continuing does export the files that were dowloaded and the transcript
   - [x] Confirm that the exported transcript includes the latest messages and replies

8. Select one file and export it:
   - [x] Confirm that displays the usual export dialog
   - [x] Confirm that export dialog title is translated when exporting a single file ("Preparing to export:…")

9. Upload a large file from a source

```sh-session
amnesia@amnesia:~$ dd if=/dev/urandom of=Tor\ Browser/10mb bs=1024 count=10000
10000+0 records in
10000+0 records out
10240000 bytes (10 MB, 9.8 MiB) copied, 0.127465 s, 80.3 MB/s
```

10. Select "Download All Files"...
11. ...and choose "Export All Files and Transcript" before the dowload finishes
   - [x] Confirm that a dialog indicates that not all files will be exported
   - [x] Confirm that continuing does display the usual export dialog
   - [x] Confirm that export dialog title is translated when exporting a single file

----

```sh-session
amnesia@amnesia:~$ dd if=/dev/urandom of=Tor\ Browser/1mb bs=1024 count=1000
1000+0 records in
1000+0 records out
1024000 bytes (1.0 MB, 1000 KiB) copied, 0.0191366 s, 53.5 MB/s
amnesia@amnesia:~$ dd if=/dev/urandom of=Tor\ Browser/3kb bs=1024 count=3
3+0 records in
3+0 records out
3072 bytes (3.1 kB, 3.0 KiB) copied, 0.000355652 s, 8.6 MB/s
```

1. Upload a few files of different sizes (3kB, 1MB, 10MB) as a source
    - [x] Confirm that you can download them as a journalist over Tor

----

PR: https://github.com/freedomofpress/securedrop-client/pull/1486

1. Create a new source and submit a message.
2. Log into the Client and wait for sync.
3. Send a reply and wait for it to send.
4. Disconnect `sd-whonix` from `sys-firewall` or run `sudo service tor stop` in sd-whonix.
5. Send at least `n >= 1` more replies.
6. Quit the Client.
7. Reconnect `sd-whonix` to `sys-firewall` or `sudo service tor start` in sd-whonix.
12. Wait several seconds.
13. Start the Client again.
14. Log in again and wait for sync.
15. [x] Observe only the first message from step (5) has succeeded...
16. [x] ...and the rest are marked `Failed to send`.
17. Repeat steps (1)‒(15), but log out (and back in) rather than quitting and restarting the Client.
14. [x] Observe only the first message from step (5) has succeeded...
15. [x] ...and the rest are marked `Failed to send`.

**Comment by gonzalo-bulnes** [comment]
> No, but that's https://github.com/freedomofpress/securedrop-client/pull/1626#pullrequestreview-1296469532. Date time-zones are localized by https://github.com/freedomofpress/securedrop-client/pull/1626.

@cfm Are you pointing out at the fact that #1626 is missing from the list of PRs in that testing step (my mistake), or that the PR is missing from the release (would be unexpected)?

**Comment by gonzalo-bulnes** [comment]
> securedrop-launcher.desktop is not usable under i3, but this worked nicely to start the SecureDrop Workstation preflight updater (I normally upgrade directly through Qubes Update):
>
> `[user@dom0 ~]$ $(cat ~/Desktop/securedrop-launcher.desktop | grep "^Exec=" | sed "s/Exec=//")`

You got out of your way to test this! The adjusted test plan seems sound to me :+1:

**Comment by gonzalo-bulnes** [comment]
> —where "localized" here means "adjusted for time-zone", https://github.com/freedomofpress/securedrop-client/pull/1626#pullrequestreview-1296469532.

:+1: Thanks @cfm. I was actually confused about that, thanks for pointing it out. Rewording the timestamps/dates are still written "in English", but match your local time zone.

**Comment by zenmonkeykstop** [comment]
## Test Plan **IN PROGRESS**

### Test Environment
Use a modified prod setup as per parent comment.

**Hardware:**  Lenovo X1 Carbon 6th-gen
**Version:** securedrop-client 0.9.0-rc2

### Testing

PR: https://github.com/freedomofpress/securedrop-client/pull/1639

- [ ] Clicking the SecureDrop icon on the desktop starts the Client

----

PR: https://github.com/freedomofpress/securedrop-client/pull/1531
PR: https://github.com/freedomofpress/securedrop-client/pull/1536

1. Start the client in Portuguese:

    ```bash
   user@sd-app: LANG=pt_PT securedrop-client
    ```
    - [ ] The Client loads in Portuguese (Portugal)
    - [ ] Dates displayed in the source list are localized
    - [ ] Date displayed at the top of the conversation is localized

- [ ] The Client loads in Chinese (Simplified):

   ```bash
   user@sd-app: LANG=zh_Hans securedrop-client
   ```

----

PR:
    - https://github.com/freedomofpress/securedrop-client/pull/1604
    - https://github.com/freedomofpress/securedrop-client/pull/1613
 
1. Seed the server with at least one source with a few dozen messages
3. Start the Client
   - [ ] Confirm that the message "Retrieving N messages" is displayed when the files are being downloaded
 
----

PR: https://github.com/freedomofpress/securedrop-client/pull/1388

1. Choose to "Download All Files"
   - [ ] Confirm that all the files for that source are displayed as "downloading…"
   - [ ] Confirm that all files are eventually downloaded
   - [ ] Attempting "Download all" in offline mode flashes message that sign-in is required
   
----

**Export All/Export Transcript Assumptions** (for general QA of export features):
    - Export all and export transcript work in online and offline mode
    - Error-handling (e.g. for wrong USB passphrase) is the same as with existing export

 PR: 
    - https://github.com/freedomofpress/securedrop-client/pull/1582
    - https://github.com/freedomofpress/securedrop-client/pull/1621
    - https://github.com/freedomofpress/securedrop-client/pull/1624
 
1. Choose to "Export Transcript"
   - [ ] Confirm that the transcript is exported, and contains all the messages
2. Send a reply
4. Choose to "Export Transcript" again
   - [ ] Confirm that the transcript that is exported includes the latest reply

PR:
    - https://github.com/freedomofpress/securedrop-client/pull/1627

1. Select a source which files are not all downloaded
2. Select "Export All Files and Transcript"
   - [ ] Confirm that a dialog indicates that not all files will be exported
   - [ ] Confirm that cancelling does that (nothing)
3. Select "Export All Files and Transcript" again
   - [ ] Confirm that the same dialog is displayed
   - [ ] Confirm that continuing does display the usual export dialog
   - [ ] Confirm that export dialog title is translated when exporting a single file ("Preparing to export:…") (PR: https://github.com/freedomofpress/securedrop-client/pull/1539)
   - [ ] Confirm that continuing does export the files that were downloaded and the transcript
   - [ ] Confirm that the exported transcript includes the latest messages and replies

5. Download all the files
6. Select "Export All Files and Transcript" once more
   - [ ] Confirm that no confirmation dialog is displayed this time, only the regular export dialog
   - [ ] Confirm that cancelling does that (nothing)

7. Select "Export All Files and Transcript"
   - [ ] Confirm that no confirmation dialog is displayed this time, only the regular export dialog
   - [ ] Confirm that continuing does export the files that were downloaded and the transcript
   - [ ] Confirm that the exported transcript includes the latest messages and replies

8. Select one file and export it:
   - [ ] Confirm that displays the usual export dialog
   - [ ] Confirm that export dialog title is translated when exporting a single file ("Preparing to export:…")

9. Upload a large file from a source
10. Select "Download All Files"...
11. ...and choose "Export All Files and Transcript" before the download finishes
   - [ ] Confirm that a dialog indicates that not all files will be exported
   - [ ] Confirm that continuing does display the usual export dialog
   - [ ] Confirm that export dialog title is translated when exporting a single file

----

1. Upload a few files of different sizes (3kB, 1MB, 10MB) as a source
    - [ ] Confirm that you can download them as a journalist over Tor

----

PR: https://github.com/freedomofpress/securedrop-client/pull/1486

1. Create a new source and submit a message.
2. Log into the Client and wait for sync.
3. Send a reply and wait for it to send.
4. Disconnect `sd-whonix` from `sys-firewall` or run `sudo service tor stop` in sd-whonix.
5. Send at least `n >= 1` more replies.
6. Quit the Client.
7. Reconnect `sd-whonix` to `sys-firewall` or `sudo service tor start` in sd-whonix.
12. Wait several seconds.
13. Start the Client again.
14. Log in again and wait for sync.
15. [ ] Observe only the first message from step (5) has succeeded...
16. [ ] ...and the rest are marked `Failed to send`.
17. Repeat steps (1)‒(15), but log out (and back in) rather than quitting and restarting the Client.
14. [ ] Observe only the first message from step (5) has succeeded...
15. [ ] ...and the rest are marked `Failed to send`.

**Comment by zenmonkeykstop** [comment]
One error hit so far with transcripts. See: https://github.com/freedomofpress/securedrop-client/issues/1643

**Comment by gonzalo-bulnes** [comment]
Calling out https://github.com/freedomofpress/securedrop-client/issues/1643 as a release blocker. :fire: 

And explicitly calling out #1644 and #1645 as **not** release blockers.

**Comment by rocodes** [comment]
Print update: No issues printing transcripts (as long as avoiding #1643) on both an HP-4001dn and on Brother HL-2360DW.

**Comment by rocodes** [comment]
Quick testing with RC3 indicates it does fix the transcript export/print crash issue. More testing TK.

**Comment by cfm** [comment]
With `securedrop-client` `0.9.0-rc3+bullseye`, all tests except launch and `LANG=zh_Hans` conducted under `LANG=pt_PT`.  Skipped some ones not of interest between `rc2` and `rc3`.


### Test Environment
- [x] Use a modified prod setup as per parent comment.

**Hardware**:
```
Qubes release 4.1.2 (R4.1)

Brand:        LENOVO
Model:        20W0CTO1WW
BIOS:        N34ET48W (1.48 )

Xen:        4.14.5
Kernel:        5.15.94-1

RAM:        48871 Mb

CPU:
  11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
Chipset:
  Intel Corporation 11th Gen Core Processor Host Bridge/DRAM Registers [8086:9a14] (rev 01)
VGA:
  Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])

Net:
  Intel Corporation Ethernet Connection (13) I219-V (rev 20)
  Intel Corporation Wi-Fi 6 AX210/AX211/AX411 160MHz (rev 1a)
```


### Testing

PR: https://github.com/freedomofpress/securedrop-client/pull/1639

- [x] Clicking the SecureDrop icon on the desktop starts the Client

Same as <https://github.com/freedomofpress/securedrop-client/issues/1637#issuecomment-1469045018>.

----

PR: https://github.com/freedomofpress/securedrop-client/pull/1531
PR: https://github.com/freedomofpress/securedrop-client/pull/1536

1. Start the client in Portuguese:

    ```bash
   user@sd-app: LANG=pt_PT securedrop-client
    ```
    - [x] The Client loads in Portuguese (Portugal)
    - [x] Dates displayed in the source list are localized
    - [x] Date displayed at the top of the conversation is localized

- [x] The Client loads in Chinese (Simplified):

   ```bash
   user@sd-app: LANG=zh_Hans securedrop-client
   ```

----

PR:
    - https://github.com/freedomofpress/securedrop-client/pull/1604
    - https://github.com/freedomofpress/securedrop-client/pull/1613
 
1. Seed the server with at least one source with a few dozen messages including some unicode☃
3. Start the Client
   - [x] Confirm that the message "Retrieving N messages" is displayed when the files are being downloaded
 
----

PR: https://github.com/freedomofpress/securedrop-client/pull/1388

1. Choose to "Download All Files"
   - [x] Confirm that all the files for that source are displayed as "downloading…"
   - [x] Confirm that all files are eventually downloaded
   - [skipped] Attempting "Download all" in offline mode flashes message that sign-in is required
   
----

**Export All/Export Transcript Assumptions** (for general QA of export features):
    - Export all and export transcript work in online and offline mode
    - Error-handling (e.g. for wrong USB passphrase) is the same as with existing export

 PR: 
    - https://github.com/freedomofpress/securedrop-client/pull/1582
    - https://github.com/freedomofpress/securedrop-client/pull/1621
    - https://github.com/freedomofpress/securedrop-client/pull/1624
 
1. Choose to "Export Transcript"
   - [x] Confirm that the transcript is exported, and contains all the messages

Also confirmed that a transcript exported under `LANG=pt_PT` is identical to a transcript exported under the default locale `en_US`, including Unicode characters.

2. Send a reply
3. Choose to "Export Transcript" again
   - [x] Confirm that the transcript that is exported includes the latest reply
4. Restart the client in the pt_PT locale and attempt to export a transcript containing ☃ unicode chars
   - [x] Confirm that the transcript is exported successfully
  

PR:
    - https://github.com/freedomofpress/securedrop-client/pull/1627

1. Select a source which files are not all downloaded
2. Select "Export All Files and Transcript"
   - [x] Confirm that a dialog indicates that not all files will be exported
   - [x] Confirm that cancelling does that (nothing)
3. Select "Export All Files and Transcript" again
   - [x] Confirm that the same dialog is displayed
   - [x] Confirm that continuing does display the usual export dialog
   - [x] Confirm that export dialog title is translated when exporting a single file ("Preparing to export:…") (PR: https://github.com/freedomofpress/securedrop-client/pull/1539)
   - [x] Confirm that continuing does export the files that were downloaded and the transcript
   - [x] Confirm that the exported transcript includes the latest messages and replies

6. Download all the files
7. Select "Export All Files and Transcript" once more
   - [x] Confirm that no confirmation dialog is displayed this time, only the regular export dialog
   - [x] Confirm that cancelling does that (nothing)

8. Select "Export All Files and Transcript"
   - [x] Confirm that no confirmation dialog is displayed this time, only the regular export dialog
   - [x] Confirm that continuing does export the files that were downloaded and the transcript
   - [x] Confirm that the exported transcript includes the latest messages and replies

9. Select one file and export it:
   - [x] Confirm that displays the usual export dialog
   - [x] Confirm that export dialog title is translated when exporting a single file ("Preparing to export:…")

10. Upload a large file from a source
11. Select "Download All Files"...
12. ...and choose "Export All Files and Transcript" before the download finishes
   - [skipped] Confirm that a dialog indicates that not all files will be exported
   - [skipped] Confirm that continuing does display the usual export dialog
   - [skipped] Confirm that export dialog title is translated when exporting a single file

13. restart the client in the pt_PT locale and select Export All on a source conversation including s ☃ unicode chars
   - [x] Confirm that the files and transcript are exported successfully
   
----

1. Upload a few files of different sizes (3kB, 1MB, 10MB) as a source
    - [skipped] Confirm that you can download them as a journalist over Tor

----

PR: https://github.com/freedomofpress/securedrop-client/pull/1486

1. Create a new source and submit a message.
2. Log into the Client and wait for sync.
3. Send a reply and wait for it to send.
4. Disconnect `sd-whonix` from `sys-firewall` or run `sudo service tor stop` in sd-whonix.
5. Send at least `n >= 1` more replies.
6. Quit the Client.
7. Reconnect `sd-whonix` to `sys-firewall` or `sudo service tor start` in sd-whonix.
13. Wait several seconds.
14. Start the Client again.
15. Log in again and wait for sync.
16. [skipped] Observe only the first message from step (5) has succeeded...
17. [skipped] ...and the rest are marked `Failed to send`.
18. Repeat steps (1)‒(15), but log out (and back in) rather than quitting and restarting the Client.
14. [skipped] Observe only the first message from step (5) has succeeded...
15. [skipped] ...and the rest are marked `Failed to send`.

**Comment by gonzalo-bulnes** [comment]
The release is done.
