### ISSUE TITLE
Draft test plan for release 0.9.0

### ISSUE THREAD

**Issue by gonzalo-bulnes** [freedomofpress/securedrop-client#1642]
For reference, all the changes included in that release are listed in https://gist.github.com/gonzalo-bulnes/b15b9a2de4a42d57338c9a02324a5fbc

## Test plan

- [ ] The Client loads in Portuguese (Portugal):
  ```bash
  (.venv) user@sd-dev:~/securedrop-client$ LANG=pt_PT .venv/bin/sd-client
  ```
- [ ] The Client loads in Chinese (Simplified):
  ```bash
  (.venv) user@sd-dev:~/securedrop-client$ LANG=zh_Hans .venv/bin/sd-client
  ```

----
 
1. Seed the server with at least one source with a few dozen messages
2. Start the Client
   - [ ] Confirm that the message "Retrieveing N messages" is displayed when the files are being downloaded
 
----
 
1. Choose to "Export Transcript"
   - [ ] Confirm that the transcript is exported, and contains all the messages
2. Send a reply
3. Choose to "Export Transcript" again
   - [ ] Confirm that the transcript that is exported includes the latest reply

----

1. Choose to "Download All Files"
   - [ ] Confirm that all the files for that source are displayed as "downloading…"
   - [ ] Confirm that all files are eventually downloaded
   
----

1. Select a source which files are not all downloaded
2. Select "Export All Files and Transcript"
   - [ ] Confirm that a dialog indicates that not all files will be exported
   - [ ] Confirm that cancelling does that (nothing)
3. Select "Export All Files and Transcript" again
   - [ ] Confirm that the same dialog is displayed
   - [ ] Confirm that continuing does display the usual export dialog
   - [ ] Confirm that export dialog title is translated when exporting a single file ("Preparing to export:…")
   - [ ] Confirm that continuing does export the files that were dowloaded and the transcript
   - [ ] Confirm that the exported transcript includes the latest messages and replies
4. Download all the files
5. Select "Export All Files and Transcript" once more
   - [ ] Confirm that no confirmation dialog is displayed this time, only the regular export dialog
   - [ ] Confirm that cancelling does that (nothing)
6. Select "Export All Files and Transcript"
   - [ ] Confirm that no confirmation dialog is displayed this time, only the regular export dialog
   - [ ] Confirm that continuing does export the files that were dowloaded and the transcript
   - [ ] Confirm that the exported transcript includes the latest messages and replies
7. Select one file and export it:
   - [ ] Confirm that displays the usual export dialog
   - [ ] Confirm that export dialog title is translated when exporting a single file ("Preparing to export:…")
----

- [ ] Confirm that actionning the SecureDrop icon on the desktop does start the Client

----

1. Upload a few files of different sizes (3kB, 1MB, 10MB) as a source
    - [ ] Confirm that you can download them as a journalist over Tor

----

1. On your test server, watch `/var/log/apache2/journalist-access.log`.
2. Create a new source and submit a message.
3. Log into the Client and wait for sync.
4. Send a reply and wait for it to send.
5. [ ] Observe exactly 1 `"POST /api/v1/sources/<uuid>/replies HTTP/1.1" 201`.
6. Disconnect `sd-whonix` from `sys-firewall`.
7. Send at least `n >= 1` more replies.
8. Quit the Client.
9. Reconnect `sd-whonix` to `sys-firewall`.
10. [ ] Observe exactly 1 `"POST /api/v1/sources/<uuid>/replies HTTP/1.1" 201`.
11. Wait several seconds.
12. Start the Client again.
13. Log in again and wait for sync.
14. [ ] Observe only the first message from step (5) has succeeded...
15. [ ] ...and the rest are marked `Failed to send`.
16. Repeat steps (1)‒(15), but log out (and back in) rather than quitting and restarting the Client.
17. [ ] Observe the same results.

## Bonus: bootstrapping case

1. Delete your `svs.sqlite` and reinitialize it with `alembic upgrade head`.
2. Log into the Client and wait for sync.
3. [ ] Sources and submissions are retrieved and displayed as usual.

----

1. Start the client in French:
   ```bash
   (.venv) user@sd-dev:~/securedrop-client$ LANG=fr_FR .venv/bin/sd-client
   ```
   - [ ] Confirm that the dates displayed in the source list are localized
   - [ ] Confirm that the date displayed at the top of the conversation is localized

**Comment by gonzalo-bulnes** [comment]
@rocodes Here is what I think we should test. I know your intention is to provide extra-detailed instruction when it comes to the setup of the testing workstations. Can you help me with that?

**Comment by rocodes** [comment]
Hey, this is great and very detailed, thank you. 

Here's my feedback:
- If possible it's good to include the PR(s) we're testing against in each test section, so QAers can refer back to original issue STR or PR documentation if they need more information
- Let's start with developer setup instructions, although we may need to finalize these as a team (eg: "From a Qubes Prod Setup, clone sd-small-bullseye, import the test key [link to apt-test key], set this template as the template for sd-app, and install the test package from apt-test into this template. Shut down the template and start the client with X command. Verify you are using the correct package with `apt-cache policy securedrop-client` in sd-app" or whatever).  These are the details that lead to misunderstanding unless we standardize our process.   
- We tested a lot of these features pretty thoroughly before merging them, so if I were looking for pre-release QA, I would probably be looking for bugs/interactions between features that we might not have noticed when testing one feature specifically. Historically, our test plans have been very much like "take the test plans for all the features and have QAers step through them," but that means we are double-testing and making it arduous. 
So I'm thinking we should define the expected behaviour (e.g.: "Export *, Print * work in offline mode"; "Export error handling is also true for Export Transcript", or "last refresh text is always visible") and request/encourage some creative testing of those features (eg: Download all then export all before download all completes, what happens?).
- As above: some of the test plans include the "happy path"(s) but not the real-world edge cases (network drops, user inputs bad passphrase, etc) -- we don't have to cover all of them in each plan but we should note expected behaviour.
- In the "failed replies are shown as failed" scenario,  is the "**exactly 1** "POST /api/v1/sources/<uuid>/replies HTTP/1.1" (emphasis added) important? A user could be slow to disconnect and/or find the logs and there could be more than one sync, i.e more than one reply post. I think the important part is the replies are marked as failed. But I would know for sure if I had the linked issue so I knew what I was testing :)  To be extra friendly I would add "disconnect sd-whonix by issuing a `sudo service tor stop` in sd-whonix terminal"  (again, overexplaining) so that people all do the same thing.  

I can help integrate these changes if you can put the issue #s beside each test portion. Just wanted to share my thought process.

**Comment by gonzalo-bulnes** [comment]
Yes all the way @rocodes. In particular, I think you're absolutely on point when it comes to the scope and goals of QA: those should not be a replay of testing individual features. :bulb: 

> Let's start with developer setup instructions […]

Yes, I'll need a hand with that.

> So I'm thinking we should define the expected behaviour […] and request/encourage some creative testing of those features […]

Yes too. Let's have a chat and summarize it here?

**Comment by gonzalo-bulnes** [comment]
Copied over to https://github.com/freedomofpress/securedrop-client/issues/1637#issuecomment-1468940421 Thanks @rocodes !
