### ISSUE TITLE
Configuration management on workstations

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#2]
information we should be storing in a config file includes:

- location of local database on workstation
- name of AppVM running the api proxy (`sd-journalist` for now)
- what else?

(Note that the journo onion URL and HidServAuth token will be stored in dom0)

I propose we just use `ini` files as it's sufficient for our purposes here and their parsing is in the stdlib

**Comment by heartsucker** [comment]
> - location of local database on workstation

This will be hardcoded to the `--home` directory passed in via the CLI and defaults to `~/securedrop_client/svs.sqlite` (see #43)

I think we should stick with the `~/securedrop_client/`directory as being the dumping ground for everything, and then have a `config.json` (or `.ini`, one of the two) with the values we need.

**Comment by redshiftzero** [comment]
I'm onboard with keeping `~/.securedrop_client` as the dumping ground. What about:

`~/.securedrop_client/logs` -> logs (creative eh?)

`~/.securedrop_client/data` -> config, database, files (submissions, messages)

regarding it being a hidden directory: users won't actually be touching anything in here unless something goes quite wrong (i.e. they're not going to be using the file manager to dig around, the client is going to be performing these actions)

**Comment by redshiftzero** [comment]
just thought of something else we should store in this config file: `use_securedrop_proxy` which should default to True (we will use this when creating the API object [here](https://github.com/freedomofpress/securedrop-sdk/blob/master/sdclientapi/__init__.py#L52)). The value in production is True, and the value in development (for those not using a Qubes workstation) is False.

**Comment by kushaldas** [comment]
>just thought of something else we should store in this config file: use_securedrop_proxy which should default to True (we will use this when creating the API object here). The value in production is True, and the value in development (for those not using a Qubes workstation) is False.

Giving options which users can change is dangerous :)

**Comment by redshiftzero** [comment]
Hey @kushaldas - so we have the data and logs directories now - want to add the config? I think it makes sense to do #30 and #31 at the same time since they are relatively small

**Comment by kushaldas** [comment]
As I went through more examples on packaging, configuring and also the database up-gradation steps in various projects, I have the following suggestions.

- Default path for the configuration file: `/etc/securedrop-client/client.ini`  This will be dropped by the deb package and will be updated (if required) by salt. I would suggest to have the default settings already into the configuration file so that we minimize work on the salt side. The file should stay at `./files/config.ini` in the source code. 

- Default path of the `alembic.ini` should be `/etc/securedrop-client/alembic.ini` and the `alembic` directory should get dropped into `/usr/share/securedrop-client` directory using the debian package. This should also have the default correct paths. Otherwise, we have to update that using salt. https://src.fedoraproject.org/rpms/pagure/blob/master/f/pagure.spec#_248 is the example 

- The actual executable in the PATH from the Debian package, should first run the `alembic -c /etc/securdrop-client/alembic.ini upgrade head`  first, and then start the client entry point. The app by default should check `/etc/securedrop-client/client.ini`  path for the configuration.

- For development purpose, we can use `python -m securedrop_client -c ./files/config.ini` command in `run.sh`. Before this step, `run.sh` should also create the db in the right path.

Now, this may sound a lot of extra work for a standard Python developer's point of view, but, these steps will insure that we will be able to package the tool into a Debian package (along with the virtualenv at `/opt/venvs/securdrop-client` and we will be able create/upgrade the database as required.

I will start working on the coding part for the same.
