### ISSUE TITLE
Changing Journalist Codename causes old content to be hidden

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#238]
# Steps to reproduce

1. Submit a message as a new Source through the Source Interface
2. Refresh the client to fetch the message
3. Through the web interface, click "Change codename" to rotate the journalist codename for that source
4. Refresh the client

# Expected behavior

The client updates the source codename and retains all messages/documents

# Actual behavior

(On `master`, 660f5a0392e9b3705485467719a6b52d0a57c242, development environment)

The client shows "Content deleted" overlays for previously received messages. Subsequent messages from the same Source are successfully synchronized.

**Comment by creviera** [comment]
## Bug

The filenames in the `data` directory use the old `journalist_designation` and the filenames in the `submissions` table uses the new designation. When the client displays all the conversation items for a source, it tries to grab the files in the data directory using the filenames stored in the `submissions` table, which will not exist.

## Proposed solution

As discussed with @redshiftzero, we don't need to update the names of old submissions in the `submissions` table. This keeps our code simpler since we will no longer need to overwrite filenames in the table or add new logic that keeps track of old source names.

**Comment by creviera** [comment]
The proposed solution above would change the current behavior of SecureDrop since it is a server-side change.

## Current Behavior

Here you can see `true hairdressing` was renamed to `unwanted plotter` and how both the source name and the old filenames change.

![screenshot from 2019-02-14 16-17-29](https://user-images.githubusercontent.com/4522213/52826506-00405100-3076-11e9-8f0c-a17fecd2d61f.png)

## New Behavior

Here you can see `waiting sigmoidoscopy` was renamed to `activating supernova` and how only the source name changes (not the old files).

![screenshot from 2019-02-14 16-05-41](https://user-images.githubusercontent.com/4522213/52826513-07fff580-3076-11e9-843b-b7fc0d5d7866.png)
![screenshot from 2019-02-14 16-05-54](https://user-images.githubusercontent.com/4522213/52826520-0c2c1300-3076-11e9-9402-6e7db18be2c6.png)

**Comment by redshiftzero** [comment]
Ahh thanks for digging into this @creviera. So I forgot that the server side was renaming files, but it makes sense since journalists who renamed sources mid-conversation using Tails could otherwise be very confused. This is because without renaming files, their correspondence (kept in a folder on their airgapped secure viewing station) would have an odd discontinuity like `['1-spoiled-potato.msg', '2-spoiled-potato.msg', '3-new-name.msg']`. If they're not dilligent about organizing files, they might not be sure these files correspond to the same source. 

It's worth noting that even with renaming files on the server side, the journalist designation changing can still lead to confusion if the journalist does not re-download the entire conversation and bring the renamed files across the airgap, meaning that they will still have this discontinuity.

Given this is a server-side behavior, it seems like the most reasonable thing to do is to copy the server-side behavior here in the client: that is, when the journalist designation changes, to rename the files locally. This is being done on the database level as you correctly point out, but the missing piece is to rename the files in the client data directory. What do you think?

**Comment by creviera** [comment]
@redshiftzero - Ah, I see. So the filenames help the journalist group submissions together after they've been transferred to the air-gapped secure viewing station. 

> It's worth noting that even with renaming files on the server side, the journalist designation changing can still lead to confusion if the journalist does not re-download the entire conversation and bring the renamed files across the airgap, meaning that they will still have this discontinuity.

Good point, and good user story. Luckily, with the client and unified workstation, this will be less of an issue since there will be fewer file transfers from the Qubes workstation (only a transfer to the publishing area is needed, I believe). 

I agree that we should provide feature parity with the journalist interface + SVS, which means changing the journalist designation as well as the files on the filesystem, and then do more user research! :)
