### ISSUE TITLE
de-mock the overly mocked tests

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#263]
Some of our tests are so mocked that they don't effectively test the code. We should review the tests to ensure we're only using the bare minimum amount of testing necessary to check functionality.

Example of over-mocking a test:

```python
def test_find_new_replies(mocker):
    mock_session = mocker.MagicMock()
    mock_reply = mocker.MagicMock()
    mock_reply.is_downloaded = False
    mock_replies = [mock_reply]
    mock_session.query().filter_by() \
                        .all.return_value = mock_replies
    replies = find_new_replies(mock_session)
    assert replies[0].is_downloaded is False
```

**Comment by eloquence** [comment]
Since this issue was filed, we added functional tests, which provide useful additional coverage. A useful next step on this issue may be for someone who has not done a lot of client work historically to inventory the current test coverage, and make recommendations for potential improvements (de-mocking or otherwise).

**Comment by gonzalo-bulnes** [comment]
I can keep this in mind as I do other things. I've removed a couple of tests that became redundant with my changes, and couldn't help but notice they were indeed quite heavy on mocking. If I find any that is mocking the object under test I'll call it out.

**Comment by creviera** [comment]
Today, we discussed order of operations here:

1. Split up the massive `widgets.py` file and subsequently the `test_widgets.py` file without refactoring the existing tests.
2. Once we're set up, we can begin refactoring any test that is not actually testing anything because it's overly mocked.

I'm closing this issue in favor of more narrowly scoped issues, plus the code referenced in the issue description looks like it has been fixed for years. It even makes sense to just open a PR without an issue if it only takes 5 minutes to fix.
