### ISSUE TITLE
Hide main window and add offline mode link to login dialog

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#286]
## Description

* Do not show client main window on launch until user logs in or clicks on offline mode link from the login dialog
* Implement hyperlink to offline mode as shown in https://projects.invisionapp.com/share/72OJI1R8DTF#/screens/325169631

**Comment by ninavizz** [comment]
Text edits: 

- `Sign In to use this newsroom's SecureDrop Workstation`
  - ...since we don't yet capture newsroom names.
- `Passphrase`
  - ...since that's existing SD nomenclature.
- `2-Factor Number`
  - ...since the designer was just being lazy and accidentally left 2FA in the above wireframe.
  - Note to @eloquence and @redshiftzero: I've flipped-back to 2-Factor, from 2-Step, after poking around some more and looking at other naming conventions against what their patterns are. 
    - "2-Step" appears to be used when it's a text-message or some other service-side action a user needs to respond to, whereas "2-Factor" appears to be used when an RSA-token kind of application is used for users to auto-generate the disposable numbers. 
    - Happy to discuss in more depth. 
    - My efforts to fish around for conclusive research evidence garnered none. :(

**Comment by creviera** [comment]
Styling for this issue has been moved to here: https://github.com/freedomofpress/securedrop-client/issues/311
This issue focuses on no longer showing the main window when the application launches until the user logs in or clicks on the offline mode link in the login dialog.
