### ISSUE TITLE
Consider how to bootstrap the database at first run

### ISSUE THREAD

**Issue by joshuathayer** [freedomofpress/securedrop-client#31]
DB needs to be created somehow either before first run (as part of package installation) or at first run.

In addition, migrations need to be applied also as part of package the installation/upgrading process, or at application startup time.

**Comment by heartsucker** [comment]
I was thinking about this, and I don't know if it make sense for us to do it at `postinst` because we're allowing for configurable home directories. This should be done at app start, possibly with an "upgrading..." spinner.

**Comment by redshiftzero** [comment]
taking a step back, i think the correct behavior is if the configuration directory is deleted entirely, running the application again should create it

**Comment by heartsucker** [comment]
Correct. That is the current behavior in the PR I have open, and adding alembic to that should be simple. In dev, there could be a switch / env-var to use `db.create_all()` to make it easier to develop.

**Comment by ntoll** [comment]
Umm... why Alembic? Surely that's a DB migration tool we'd use as developers. SqlAlchemy creates the database on first run anyway. As we iterate on the application we can just recreate the database anyway on first run (i.e. 2.0 knows there may be a 1.0 version of the database, but cleans this up and re-syncs using the new 2.0 schema of the DB). 

I'm anxious we don't add more complexity at this stage than we really need to. YAGNI etc... ;-)

**Comment by heartsucker** [comment]
If we want to remote a column from a SQLite db after an upgrade, SQLAlchemy won't know how to "create" the removed column. Continuously applying `Base.metadata.create_all(engine)` will work up to a point, but anything remotely complex requires a migration too. This bit us in the ass in SecureDrop core and there were features that got blocked or pulled from releases because we couldn't support them.

IMO `alembic` (or some other tool, but really hopefully `alembic`) is a hard requirement for the initial release of the client.

**Comment by ntoll** [comment]
@heartsucker absolutely get that.

But given that the database will only ever contain data sync'd from the server anyway (and I concede I'm playing devil's advocate here), and a sync pulls "the universe" at the moment, I'm trying to imagine why we'd need this, IYSWIM. In my mind's eye, the "migration" would be:

* Stash the old version somewhere
* Completely recreate the new database with the new schema
* Sync the universe
* Voila..!

Does that make sense.... or am I missing something here? (Very likely) ;-)

**Comment by heartsucker** [comment]
> a sync pulls "the universe" at the moment

Maybe I'm *out of sync* (slaps knee), but wasn't the assumption that the local client could have data that was deleted from the server? This would mean that "pull the universe" would cause data loss in the event of a dump-then-recreate. Additionally, because Tor is slow, if someone locally has many files, we wouldn't want to redownload them. It would be easier to put the burden on the devs to implement a migration than to offload that to the app/network.

And even if we "stash" it, we have just turned an alembic migration into a hand-rolled migration. Also, even if we concede that hand rolled migrations are better, we already have a pretty robust test suite for the alembic migrations implemented in SecureDrop core, so we could port those rather easily and the have robust testing for alembic migrations.

**Comment by redshiftzero** [comment]
so @ntoll makes a good point here - we _can_ just resync everything which seems significantly simpler

> the assumption that the local client could have data that was deleted from the server

right now deletion is global and immediate, though we do want to eventually implement a trash workflow. when we do that, the server will be also storing the files that are in a user's trash. 

the only local-only storage we have is whether or not a file has been downloaded. if we abandon the alembic route, we'd have to implement some logic where we mark as downloaded any file that's in the data directory, but this is very straightforward. 

> if someone locally has many files, we wouldn't want to redownload them

again we wouldn't redownload files, instead we'd just resync, mark those that exist on disk as such

> if we "stash" it, we have just turned an alembic migration into a hand-rolled migration

well I think @ntoll was suggesting we stash it just for safe keeping (i.e. in case an upgrade fails for some reason), but otherwise we don't write any migration at all - hand rolled or not. we just create the new database, and then fetch from the server. in terms of the time this would take over Tor, we're doing it anyway when we sync the API, so it shouldn't take any extra time. this is simpler... as then we don't need to both writing either migrations or migration tests (if we choose this path we should also not preserve alembic for developer use as it wastes developer effort on writing migrations).

**Comment by redshiftzero** [comment]
discussed with @heartsucker just now and there is one hiccup due to our support of offline mode: an existing user should be able to: 

1. start their workstation and do system updates first (e.g. if the user hasn't used SecureDrop in a while)
2. use the workstation in offline mode only

this is unfortunately not possible if we recreate the database on upgrade... so we should keep alembic.

**Comment by redshiftzero** [comment]
closed by #86
