### ISSUE TITLE
Application should exit when cancelling initial login

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#318]
Follow up to #313

When the app is started, only the login dialog is visible. If you cancel the dialog, there is no way to bring it back up, so the app enters a state where it can not receive used input and is "hung". The app should quit (or just not allow a user to initially cancel).

## STR

1. Start app
2. See login
3. Hit escape / cancel

## Expected Results

App terminates **or** it shouldn't be possible to cancel the login when no other windows are visible.

## Actual Results

App runs in background forever

**Comment by creviera** [comment]
> App terminates or it shouldn't be possible to cancel the login when no other windows are visible.

The way a user can exit the app is by clicking the 'x' icon of the login window before the main window opens, or by clicking the 'x' icon of the main window once it's open. I don't recommend removing a user's ability to close the app when they hit the 'x' icon of the login window if it's the only window a user has to interact with the app.

If we want to support a hot-key to close the application, I think it would make more sense to use `command-q` or `ctrl-q` rather than 'Esc'. I haven't come across an 'Esc' standard for closing applications. Do you know of any other desktop applications that close when you hit 'Esc'?

**Comment by ninavizz** [comment]
@heartsucker When you say "cancel the dialog" in your initial comment, do you mean the same thing Allie references in "clicking the 'x' icon"?

I think I agree with Allie's recommendation—even before we properly implement hot-keys across the Client (post-Beta, I'm thinking, for that).

**Comment by eloquence** [comment]
I'm only able to replicate this bug by pressing the `[Esc]` key, closing the window works as expected. I also don't see any other way to "cancel" the dialog.

**Comment by heartsucker** [comment]
> I'm only able to replicate this bug by pressing the `[Esc]` key, closing the window works as expected. I also don't see any other way to "cancel" the dialog.

Yeah that's actually correct. I'm so used to hitting Esc that I just assumed there was also a cancel button on that popup. :sweat_smile:

**Comment by ninavizz** [comment]
Hey gang—the name of this Issue is a tad confusing.

1. There will be a "Cancel" button on the login, from Offline mode. You're not suggesting that, que?
2. If the user opts to close the VM by clicking the "x" on the initial Login window, then yes; but that should be a standard behavior client-wide, not just on login.

I'd rather not sweat Esc key details, for Beta. A keyboard shortcut to quit the app, yes—but there's so much more we need to get user feedback on from Beta, than makes getting keyboard shortcuts a big value add at this stage.
