### ISSUE TITLE
consider keyboard shortcut for closing the client

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop-client#35]

**Comment by ultimatecoder** [comment]
@heartsucker I request to elaborate the situation/behavior after user session is quieted/exited. Below are confusions I have.

1. Should SecureDrop client be closed once the user press that button?
2. How is this behavior different from User pressing a "Logout" button? Do you think existing messages should be disappeared as if no user is logged in?

Thanks!

**Comment by ninavizz** [comment]
I intentionally did not design for this in the UX, and it's my preference to not see this functionality. 

Rationale: our non-technical users are unlikely to want to close the Client within the VM; closing the VM itself, is what I anticipate the preferred method to be (so therefore would rather not have additional UI elements cluttering the Client). I advised Nicholas early on to please have the client UI set to fit within its VM window at max-height and max-width. When keyboard shortcuts are introduced a Ctrl-Q type functionality would be fine to build-in, but again—I don't want the UI element cluttering the GUI. 

Thoughts?

**Comment by ultimatecoder** [comment]
@ninavizz Thanks for explaining reasons in detail. I agree, it will be batter to not confuse a User with two close icons. @heartsucker What are your thoughts? Thanks!

**Comment by ninavizz** [comment]
P.S.: It's great having you on board for the Workstation, @ultimatecoder! My comment above reads rather terse/defensive, which I regret—but did want to let you know that I do appreciate everyone on the team caring & piping-up about the UX; it's much more fun for everyone (including me) that way. In all my years of UX, I definitely think a better product gets shipped when everyone cares/contributes—vs everyone keeping neat/quiet in our little silos! :)

Also great having you in the UX meetings! Keep it coming! :)

**Comment by ultimatecoder** [comment]
@ninavizz Your comment isn't terse at all.  You shouldn't regret about it. I am enjoying all the discussions happening in UX meetings. I will try to never miss them out. More eyes will bring more perspectives.

**Comment by ultimatecoder** [comment]
@ntoll Great question! I was assuming that the app will only run at Qubes (because of its security reason). I would like to point out that @ninavizz  already mentioned the point of creating a shortcut (CTRL+q) for closing the application. One can use that keyboard shortcut to close the running application.

**Comment by ninavizz** [comment]
@ultimatecoder Agreed wrt more eyes/brains, and hooray! :) 
Also: yes, yes, to CTRL+q and a Client in Beta packed with allteh keyboard shortcuts. 

@ntoll You assume, I assume—we all assume! 🗡 

Qubes is such a wonky thing. We're really hoping to get more non-technical users in newsrooms engaged. A common refrain in testing has been "Yah, it's currently just myself and Joe Blow checking the SD every other week—we wanted to do it every few days, but we don't have time—we trained two of our other colleagues, too, but they never got into using it..."

As such, I'd like to keep the Client as specific to Qubes as possible, as we're working with so many conflicting mental models and new mental models with the non-technical users. It's normal for most apps to be specific/native to Linux, Mac, or Windows, as each OS has its own quirks (and even tho Mac is technically Linux); and I see Qubes as a 4th category... as it's not at all about a unique GUI or OS-y functionalities, but rather compartmentalization and security—which then introduce their own unique bouquet of user expectations, adaptations, and learning needs. /cc @eloquence Thoughts?

**Comment by heartsucker** [comment]
> In any case, I think your reasoning still applies since non-Qubes OS has the Window chrome of the host OS including a close "x" area in the title bar.

I'm using xfce / xmonad, and I have no way to kill it without using `^C` or `kill`.

**Comment by heartsucker** [comment]
Not saying we should add the `quit` button as I agree with @ninavizz, but just sayin' for the sake of completeness.

**Comment by ninavizz** [comment]
We definitely will need to coordinate with whomever is designing the Qubes Templates, to make sure windows are configured correctly; but my recommendation is based specifically around how Qubes does its windows. For devs & possibly admins, a CTRL-Q couldn't hurt; not sure how I could include this in user research, but I'll note as an open curiosity point it for sure. 

When I get around to doing the visual design (colors! final icons!) for Beta, my inputs will be rooted in how this thing will look w/in a Skittles-colored Qubes window with the three buttons in the top-right, and the VM's name on the top-left. To the average user, the Qubes skittle-window chrome will appear to be the most external-layer of a Client chrome—and I want to run with that, since it's easier than fighting it (and lends to the threat model of keeping other apps from running in the same VM).

**Comment by ntoll** [comment]
Adding a shortcut for CTRL-Q to close the app would be easy to implement. Happy to do so if it means we can close this ticket.

**Comment by eloquence** [comment]
Nice to have and hopefully easy, marked as stretch for beta.

**Comment by eloquence** [comment]
Cross-linking related keyboard navigation epic: #274

**Comment by gonzalo-bulnes** [comment]
> When keyboard shortcuts are introduced a Ctrl-Q type functionality would be fine to build-in, but again—I don't want the UI element cluttering the GUI.

I assigned myself to address this issue, it's in line with what I'm doing. (See the motivation for #1328)
