### ISSUE TITLE
Create changelog file

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#367]
## Description

Create a changelog file in this repo and add a section in the docs to explain the release process:
1. before creating a debian package, file a changelog PR
2. merge it
3. update the debian package changelog to point to the package's changelog
4. release debian package

**Comment by redshiftzero** [comment]
we should implement this because the changelog entry _should_ be something added by the RM of the individual project, not the person (packager) who checks out the tag and does the final package build / release. Ideally the packager doesn't need to know anything about the changes. This is a more reasonable separation of duties.

**Comment by redshiftzero** [comment]
This is also consistent with what we do in securedrop core: RM for the release pushes up the release branch/tag with the changelog, and then the person building the final debian packages just checks out the tag, builds, and puts up on the apt server
