### ISSUE TITLE
Handle RuntimeError when file hash does not validate

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#383]
As of #374 there's a `RuntimeError` when the sha256 hash (provided in the ETag header) on a file does not verify, see https://github.com/freedomofpress/securedrop-client/pull/374#discussion_r286640523. 

This happens when a file is corrupted during download. We need to:

* Handle this exception
* Retry the download job again

**Comment by creviera** [comment]
The client also currently interprets missing etag and non-sha256 etags as OK. Once etags are fully supported, those two conditions should also throw. Not sure if we would want to retry in the same way as an etag checksum mismatch, probably not, given that it is much less likely to be a file download corruption issue.

**Comment by creviera** [comment]
Also, I just learned from emkll that supporting missing and non-sha256 etags allows us to continue support of instances running before 0.13.0, when the install script to fix apache stripping etags was introduced. 

There is an edge case where, instead of running a clean install of 0.13, a user upgrades to 0.13 and doesn't run `./securedrop-admin install` which will update the apache config that tells apache to not strip etags.

I think it still makes sense to remove support of missing and non-sha256 etags, meaning throw an error and tell the user to run the securedrop-admin script, or maybe it can be done automatically? Otherwise we will not be able to tell if the downloads are corrupted (perhaps because of Tor flakiness).

**Comment by eloquence** [comment]
From a deployment point of view I don't see a significant issue with requiring a recent playbook run to run the client in prod environments, since we have significant control over the deploy story for the pilot. We will have to document this in the README.

**Comment by redshiftzero** [comment]
Due to necessary apache config changes for the API (for HTTP DELETE method support) regardless of this ETag situation we have to require a recent playbook run for using the client in prod environments, so we can throw errors if ETags don't validate without issue. The only annoyance really is for people testing, who need to make sure they've ran the playbook since #4023 was merged.
