### ISSUE TITLE
Create a MetadataSyncJob

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#461]
## Description

Move api calls to sync the client with the server into and ApiJob and ensure that it is called precisely every five minutes or immediately when the user clicks refresh.

## Background

The client syncs with the server every five minutes by calling [sync_api](https://github.com/freedomofpress/securedrop-client/blob/6c8118da154bb8c37f7a5ae26ec2a0eff80b7744/securedrop_client/logic.py#L350), which makes the following api calls:

* get_sources
* get_submissions (for each source)
* get_all_replies

Whenever `sync_api` returns successfully, the client then downloads and decrypts any new message or reply.

**Comment by creviera** [comment]
Note: There could be jobs in the queue for downloading and decrypting that are not finished when the next sync happens on the 5-minute mark or when the user clicks the refresh button. This is okay because jobs will only be added for new submissions or replies.

**Comment by eloquence** [comment]
Per https://github.com/freedomofpress/securedrop-client/issues/489#issuecomment-514775826 this also will help us resolve other issues, so we've agreed to prioritize it in the 10/23-11/6 sprint period, and I've added it to the alpha milestone.

**Comment by kushaldas** [comment]
I will pick up this one.

**Comment by redshiftzero** [comment]
> There could be jobs in the queue for downloading and decrypting that are not finished when the next sync happens on the 5-minute mark or when the user clicks the refresh button. This is okay because jobs will only be added for new submissions or replies.

since for a given document A its `is_downloaded` field is only going to be updated once its download job is completed, if the download job is in the queued state when the second sync occurs, the second sync will add another job for document A. For now this is OK but I think we need to add a mechanism to deduplicate queue jobs in the future - this would also handle the situation in #116 (to be fair that could be avoided with a pending status in the FileWidget to prevent the user from triggering the download again).
