### ISSUE TITLE
Show/hide conversation items

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#473]
## Description

Right now we create a conversation  when a source is selected and we delete it whenever the source is unselected. If there is a sync and new messages in the conversation, we delete and recreate it. 

Instead of deleting the conversation whenever the source is unselected, let's hide the conversation. And instead of recreating the conversation when new messages come in for a source, let's just append new message widgets to the conversation view.

**Comment by creviera** [comment]
This is follow-up for https://github.com/freedomofpress/securedrop-client/issues/467

**Comment by redshiftzero** [comment]
Here's a first proposal for the logic here:

1. get new conversation items
2. if order has changed for drawn items, redraw everything
3. else start iterating through each item
4. if the text has changed, update text on that item without redrawing the entire item
5. if the status has changed (e.g. from Pending -> Failed), update the style on the item without redrawing the entire bubble (involves adding methods on the relevant widgets to modify state without redrawing)

Note that the part that complicates the issue here is the fact that items may be reordered - since the client will update to reflect the ordering on the server.
