### ISSUE TITLE
health checker - auto resume

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#491]
## Acceptance Criteria 

Given that some operations have repeatedly failed due to network issues
When I do nothing
Then the client should periodically test connectivity
And the error message should disappear when connectivity is restored
And the queue should be resumed when connectivity is restored

**Comment by redshiftzero** [comment]
For the health checker we could add a new class (similar to the metadata sync running on a timer) that does _not_ have an API token (in the interest of keeping authenticated API calls all being triggered through a single location that is the queue). We could add an SDK endpoint to hit the unauthenticated endpoint [here](https://docs.securedrop.org/en/release-0.14.0/development/journalist_api.html#root-endpoint) - alternatively, a better thing to do would be to implement https://github.com/freedomofpress/securedrop/issues/4698 as an unauthenticated endpoint since we need it anyway for the client, and _then_ add an SDK method for that.

We're never really going to be able to distinguish 1. general network connectivity issue from 2. admin has just cycled the HidServAuth credentials, so to that end if things keep failing there should probably just be a “Talk to your securedrop administrator” message.

**Comment by eloquence** [comment]
Upon consideration, this seems like a nice-to-have feature for the beta, but not a must-have. Hopefully, once all actions are handled by the queue, errors should be rare since we do retries automatically a limited number of times. If the main reason to do this is to have the Retry dialog disappear magically when connectivity is restored, I would vote to defer to Post-Beta. Thoughts @creviera @redshiftzero ?

**Comment by redshiftzero** [comment]
I agree with this

**Comment by eloquence** [comment]
(Added to Post-Beta for now.)

**Comment by eloquence** [comment]
(Adjusted milestones again as this is being handled within #612)

**Comment by redshiftzero** [comment]
closed by #612
