### ISSUE TITLE
Cover line widget on select

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop-client#511]
# Description

Cover the "BrakeLine" between the selected source widget and the conversation view. This will require adding a BrakeLine widget, see screenshot below:

![cover-line-on-select](https://user-images.githubusercontent.com/4522213/62334725-aa256580-b47d-11e9-9b22-5815703fdb47.png)

In Zeplin, the BreakLine shows up as 3px wide with a color of #514d6e. The BreakLine should span all the way up to the top pane and down to the bottom of the client window.

**Comment by redshiftzero** [comment]
so right now we don't have this linewidget right? can we instead add a right-border via CSS styling for the unselected source list items?

**Comment by creviera** [comment]
we could update the SourceList widget's CSS to be
```
    CSS = '''
    QListView {
        border: none;
        show-decoration-selected: 0;
        border-right: 3px solid #514d6e;
    }
...
```

Which would look like:

![border-right](https://user-images.githubusercontent.com/4522213/62400129-026a6f00-b533-11e9-9cb3-ffda251b5224.png)

However the bottom line should not merge with the right line. So this moves the problem to having to add another widget in the SourceWidget so that we can add padding between it and the outer widget.

I feel like there are a number of ways to address this. It just seemed easiest to me to have a line separator that was stand-alone, but both are perhaps equally simple. The challenge in this issue will be how to show the same background image without the right border wherever the selected source widget is. I was predicting that it would be easier to do CSS/Qt tricks if we were working with a Qt line object rather than a CSS border property, but perhaps I'm wrong.

In the meantime, we just removed borders so that it looks like a selected source is part of the conversation view.

**Comment by creviera** [comment]
I'll bring this up during the next ux meeting, but we could use this code for separating the borders:
https://gist.github.com/creviera/96795a0d40cf60c36ff88cfa92f73ebd
so that it looks like:
![separate-borders](https://user-images.githubusercontent.com/4522213/62403749-592c7480-b544-11e9-9939-69189818683e.png)
but since we decided this week to go with no borders seems fine to wait

**Comment by eloquence** [comment]
Adding `blocked` for now - we don't agree that we want to move forward with this specific design pattern (given the implementation complexity), but it's worth keeping open as we discuss ways to polish the source list.

**Comment by zenmonkeykstop** [comment]
Closing as a wontfix
