### ISSUE TITLE
Add gradient to source list items

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#513]
## Description

In order to share the same background image, there needs to be a new widget to contain the source list and conversation view (view_holder to be precise) in the MainView. Once this is added, along with https://github.com/freedomofpress/securedrop-client/issues/512, the **same** background image will show up behind the source list and conversation view.

**Comment by eloquence** [comment]
Discussed in backlog review today; we'll still need to decide if we really need a gradient on the conversation view (`view_holder`), or if it will be sufficient simply to add it to the source list item.

**Comment by creviera** [comment]
@ninavizz will add updated zeplin screens to this issue

**Comment by ninavizz** [comment]
Going over my own files on this topic, I realized I decided against including a gradient in the sourcelist highlight. Ultimately, while quite neat-o and aesthetically appealing, concern arose that it would seem too "weird" to users, and thus might stoke concern there could be a GPU or some other technical/rendering issue. Because, Qubes. As such... it is with great sadness, I close this issue.
