### ISSUE TITLE
Verify basic client operations in Debian Buster VM, including Qubes-specific operations

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#528]
Preparatory to the VM/packaging transition to Buster (https://github.com/freedomofpress/securedrop-workstation/issues/306) we want to do additional testing of the client in a VM based on Buster.

@conorsch has already done some basic client testing (and it appears the CI test jobs have been happily running in Buster; see #527), but we want to do as much Qubes-specific testing as we can without switching the other templates/packages over; in particular, Conor has raised opening files in disposable VM as a useful thing to test in Qubes.

**Comment by conorsch** [comment]
So far, so good! I'm able to run the dev env in Qubes, via a Buster-based VM, and open submissions in (Stretch-based) DispVMs:

![sdc-buster-client-dev-env](https://user-images.githubusercontent.com/657862/62663170-5e663680-b92b-11e9-8f87-84129f34accc.png)

In order to test, I also ran the `make dev` containers from the https://github.com/freedomofpress/securedrop/ repo the same Buster-based VM, without issue. We should still update the CI settings to stop using python 3.5 and instead use 3.7, as that's the default in Buster, but that work is better suited to #527.

**Comment by conorsch** [comment]
In order to test, I did the following:

```
# in dom0
qvm-clone sd-dev sd-dev-buster --label blue
qvm-volume resize sd-dev-buster:root 15G # helps with container cache
qvm-tags sd-dev-buster add sd-client
```

Assuming `sd-dev` is already a StandaloneVM, `sd-dev-buster` will be, as well. The `sd-client` tag is required to permit DispVM functionality as described in https://github.com/freedomofpress/securedrop-workstation/pull/299/. 

```
# in sd-dev-buster
sudo apt-get update
sudo apt-get dist-upgrade -y
sudo apt autoremove
sudo apt autoclean
```

Then reboot `sd-dev-buster` and confirm it's running Debian 10:

```
[user@sd-dev-buster:~] $ 
 $ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

The `sd-dev-buster` VM was intended as temporary, to provide easy rollback to Debian 9 (i.e. `sd-dev`) in the event of problems. Now that I'm comfortable using Buster, I'm happy running through the same process on `sd-dev` to make it permanent. First, though, I suggest that @creviera run through the steps outlined above and confirm no problems on their machine.

**Comment by creviera** [comment]
client works on buster for me too (just had to reinstall dependencies in a new virtual env)

**Comment by eloquence** [comment]
Basic verification completed, docs updates will be handled separately.
