### ISSUE TITLE
[EPIC] Polish Export UI

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#560]
## Description

* Add a close link in the top right-hand corner
* Add a task description and update margins and spacing between the task description, error message, instructions, and button panel, see [zeplin](https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5d3e9d093de035355770bc26)
![zeplin-export](https://user-images.githubusercontent.com/4522213/65062864-d6b01680-d931-11e9-91a3-29568fbb9f64.png)
Note: There's actually a `Continue` button in the client because of how we communicate between the Export and Client VMs. If you have to use placeholder text until https://github.com/freedomofpress/securedrop-client/issues/549 is finished, that is fine. The focus of this Issue is UI styling - fonts and formatting and that sort of thing.

**Comment by creviera** [comment]
Also pay attention to:
* letter-spacing
* font styles
* button outlines
* bg color
* overlay outline

**Comment by ninavizz** [comment]
Yeah, no more "close" link in upper-right corner. :(( For the Pilot Beta release, anyway.

[Zeplin Draft](https://zpl.io/blArpK5), from **24 Nov** meeting to agree on messaging and basic flow.

Text may be copy/pasted from draft. Because there is not a specific GH Issue for content, alone, I will keep the canonical source-of-truth in copyediting for these windows, in Zeplin.

Also, see [This UX Repo Issue](https://github.com/freedomofpress/securedrop-ux/issues/57) as canonical source-of-truth for allthings Export.

**Comment by eloquence** [comment]
(We're tackling this incrementally, so tagging as epic and tracking in near-term backlog until all components are complete.)

**Comment by eloquence** [comment]
(This issue is quite dated and no longer useful as an organizing epic; we can track iterative improvements without an epic. Closing.)
