### ISSUE TITLE
Storing and Deleting hard links to doc files

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#579]
# Description

I noticed that we are [creating a hard link to files we want to open in a disposable display vm](https://github.com/freedomofpress/securedrop-client/blob/df66f46ab5b51e49a7e80e013d44d57f44d6e40d/securedrop_client/logic.py#L588-L590) with the `original filename + extension` in the client. In some cases we are unable to [extract the original filename from the header of the gzipped file](https://github.com/freedomofpress/securedrop-client/blob/df66f46ab5b51e49a7e80e013d44d57f44d6e40d/securedrop_client/crypto.py#L46-L75) so [the original filename is set to the download filename](https://github.com/freedomofpress/securedrop-client/blob/df66f46ab5b51e49a7e80e013d44d57f44d6e40d/securedrop_client/storage.py#L398-L402) (e.g. `<fileno>-<journalist designation>-doc.gz.gpg`). The file is still decrypted but we don't know it's type and won't be able to open it. However we're currently still trying to open it as `doc.gz.gpg`.

A couple more things to note about how we are storing files in `sd-svs`:

* We have to remember that even though a hard link allows two different files to point to the same content, deleting one file will not delete the other. This is important when we remove files associated with a source.

* The file with the `original filename+extension` will not exist on the filesystem unless the user attempts to open it.

* The current fire-and-forget method of opening documents in a separate VM makes it so we don't know when the file has been successfully transferred to the target VM, therefore we don't know when it is safe to remove the hard link. 

* In some cases we are unable to [extract the original filename from the header of the gzipped file](https://github.com/freedomofpress/securedrop-client/blob/df66f46ab5b51e49a7e80e013d44d57f44d6e40d/securedrop_client/crypto.py#L46-L75) so [the original filename is set to the download filename](https://github.com/freedomofpress/securedrop-client/blob/df66f46ab5b51e49a7e80e013d44d57f44d6e40d/securedrop_client/storage.py#L398-L402) (e.g. `<fileno>-<journalist designation>-doc.gz.gpg`). When a user tries to open it, we will create a hard link to the filename `<fileno>-<journalist designation>-doc.gz.gpg` and try to open it and fail.

# A way to clean things up

Create a hard link for every file during the decryption stage, after we successfully extract the original filename from the header. If we can't extract the original filename, then store `original_filename` as `None` instead of the `<fileno>-<journalist designation>-doc.gz.gpg` filename.

When we try to open the document, instead of deleting then creating a hard link it should just check to see original_filename is not None and if the path to the hard link exists before attempting to open it.

For export, I think it would make sense to fall back to exporting the decrypted document that has no original_filename associated with it.

When we delete files associated with a user, we need remember to delete both paths with the different filenames.

**Comment by eloquence** [comment]
> In some cases we are unable to extract the original filename from the header of the gzipped file 

Since SecureDrop itself creates gzip with filenames in the header, should we treat gzip with missing header information as effectively corrupt and handle it more like an error, earlier in the process? Or is there a technical reason (e.g. legacy behavior) why sometimes we will legitimately encounter gzip files without filenames in the header? (cc @redshiftzero)

**Comment by creviera** [comment]
I like this idea. If we put the original filename in the header when we send it, yet it's not there when we decrypt it, I think it makes sense to not set `is_decrypted` to `True`. `True` indicates that we were able to successfully decrypt and get what we needed.

**Comment by rmol** [comment]
It might be better for diagnostics and error correction to not conflate decryption with validating the decrypted file. If it were properly decrypted but the content were bad, there'd be little point in downloading and decrypting again (because we've got what the server's got, and probably can't fix whatever's wrong with it), but if decryption failed, it would be reasonable to suspect the download was corrupt and to try fetching and decrypting again.

In the specific case of a gzip header without the original filename, it might be possible to infer what's in the archive with [python-magic](https://github.com/ahupp/python-magic), but unless there's a historical reason the filename could be missing, I'd vote for just showing an error and pointing the journalist to an administrator. (Though ultimately there's probably not much to do but delete that item on the server.)

Will have to get back into this code and think on my sins before commenting on the main points of this ticket. :slightly_smiling_face: 

Actually, we could create a temporary directory when exporting, copying the exported items there. Then the original item could be safely deleted while the export was in process, and the temp dir deleted after export (and probably also at startup, to clean up after crashes or otherwise interrupted exports).

**Comment by creviera** [comment]
There's still the problem of creating hard links to the file in the `on_file_open` method when the user tries to open a document. I think it makes sense to either a) clean up after opening the file so that we're not left with two files (this will require some refactoring because of the fire-and-forget behavior mentioned above - we could change the `on_file_open` method to be more like the `export_file_to_usb_drive` method so that we can figure out when the check_call finishes and know when to clean up), or b) create a hard link as soon as we extract the orignal_filename and just expect there to always be a hard link to the original file for every decrypted file on disk.

The quickest way for now would be to create a hard link as soon as we extract the orignal_filename. We could hold off on setting `is_decrypted` to False if we can't get the filename and still fix the couple bugs here by checking if `original_filename` exists, however I think this makes the code messier since it really is an error if we can't get the original filename, right? And filename extraction _is_ part of the decryption stage.

I agree, if the original filename cannot be extracted, there should be logging for better diagnostics as @rmol mentioned. We currently have a `CryptoError` and logging around exceptions during decryption, so it would be easy to use our queue and exception handling and communication for a new custom exception like `MissingFilenameCryptoError`. Then we can prevent the user from trying to open `gz.gpg` files.

**Comment by eloquence** [comment]
>  unless there's a historical reason the filename could be missing

In my own digging I was not able to find evidence of such. When SecureDrop switched to gzip for submissions in 2015, filenames were already included in the archives:

https://github.com/freedomofpress/securedrop/commit/88f6ea9b304232a2f55ac2ca09ae3b414660c73f#diff-faabd6620c3a9c1443f7eedd78f23e27R103

Therefore, it would IMO be safe and correct to treat gzip archives without filenames as wholly unsupported.

**Comment by redshiftzero** [comment]
taking a step back: do we need these hard links? I think it's a lot easier to reason about the application's behavior if keep as much state as possible stored in the database. We could remove the hard links entirely if we:

* modify the sync logic to not download a message or reply if `is_downloaded=True` 
* don't overwrite `filename` for objects that are downloaded since `filename` will be set to the original if extraction completes.

Then the application accesses whatever is on `object.filename` for export and open. When `object_filename` is deleted, then it's gone and we don't need to clean up any hard links.

**Comment by eloquence** [comment]
Sounds like we have a consensus on how to proceed, can we close this in favor of #714?

**Comment by creviera** [comment]
yup! closing in favor of this issue: https://github.com/freedomofpress/securedrop-client/issues/714
