### ISSUE TITLE
Format placeholder text and hide on focus

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#594]
## Description

Currently the text `Compose a reply to [sourcename]` remains in front of the cursor in the ReplyBoxWidget until you start typing. It should be removed as soon as soon as textbox is active. It also needs to be updated so that it is formatted to match the Zeplin screen so that the source name is:

* font and font size: Montserrat-Bold
* size: 18px
* letter spacing: 0.25px
* color: #24276d

and the `Compose a reply` part is:
* font and font size: Montserrat-Regular
* size: 18px
* color: #404040

**Comment by deeplow** [comment]
It seems that we are fighting against the nature of Qt. Here are my findings so far:
- `QTextEdit.setPlaceholderText()` does NOT allow html as input (although this is not documented)
- `QTextEdit.setText()` allows for html but for some reason it does not work if we wanted to set it as a "placeholder" (meaning that we cannot `setText` as soon as the text box is created) - again, undocumented behavior.

We need the html in order to format the source name with bold.

Probably just adding a label on top the text box with the formatting is the best we can do to circumvent these limitations
