### ISSUE TITLE
Intermittent "The SecureDrop server cannot be reached" errors

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#610]
During normal operation of the client in Qubes, connected to a prod instance, the error "The SecureDrop server cannot be reached" intermittently appears and won't go away until you press "Retry". 

My understanding is that this is due to failed metadata syncs and will be mitigated through #461, but tracking separately in case there are additional short term mitigations that we can put in place quickly.

**Comment by redshiftzero** [comment]
If the retry logic is being hit here, then this particular intermittent network error is something that #461 won't fix since it's happening due to failed download reply/message/file jobs (but we still need to do #461 as there are intermittent network errors also due to that action failing, they just don't trigger the retry logic). Two strategies to fix this are:

1. Increasing the number of automatic retries up from 5, this is transparent to the user
2. This is an interesting idea that @creviera had - we add a more lenient job class that we allow to fail and keep enqueuing until it finishes (fine for actions like message download)

We can start with 1 and if we still see issues unpack 2 a bit more
