### ISSUE TITLE
Placeholder messages display with HTML entities

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#644]
As of the December 6 nightly build, I see the following placeholders in Qubes when messages haven't been downloaded yet:

> `&lt;Message not yet available&gt;`
> `&lt;Reply not yet available&gt;`

Instead of the expected

> `<Message not yet available>`
> `<Reply not yet available>`

**Comment by kushaldas** [comment]
I can reproduce this.

![wrong_ui_before_decryption](https://user-images.githubusercontent.com/272303/70990810-4d54df80-20ec-11ea-9425-1f663943a7a4.png)

**Comment by kushaldas** [comment]
This is due to the `html.escape` introduced via https://github.com/freedomofpress/securedrop-client/commit/dcce99f7beefc47bd89292fb1fe92e7977ff6000  commit. This helps to mitigate against any random random attack in the message text. 

My suggestion is to just remove `>` and `<` characters from any such message. @eloquence @redshiftzero @emkll your thoughts?

**Comment by emkll** [comment]
related to https://github.com/freedomofpress/securedrop-client/issues/645

**Comment by eloquence** [comment]
I don't especially care about the use if these characters in the placeholder text (long term we want to use a different loading pattern anyway), but I do feel iffy about characters that should be safe when handled responsibly not working here. :/ And I do think we must resolve #645.
