### ISSUE TITLE
"Sign in to compose or send a reply" placeholder sometimes cut off

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#663]
See this screenshot:
![Screenshot_2019-12-12_20-23-52](https://user-images.githubusercontent.com/213636/70762975-641fbe80-1d07-11ea-9081-43ea58e5e1cd.png)

So far I've only been able to produce this issue with the highlighted source (not with other sources!) on our test server by following the steps in #662, but this may arise under other circumstances as well.

**Comment by deeplow** [comment]
I would assume this has something to do with the fact that the placeholder is a `Qlablel` rather than being text on Reply textbox itself (to support rich text over a textbox that does not - from https://github.com/freedomofpress/securedrop-client/pull/597). For some reason, the label must have not scaled to the text.

**Comment by eloquence** [comment]
I'm not able to repro this issue anymore on current git `master` testing with multiple sources, so closing for the time being.
