### ISSUE TITLE
ReplyBox sourcename sometimes no longer disappears after sending a reply

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#691]
# STR

1. Send a reply
2. Type in a new reply and see that the source name no longer disappears

![Screenshot from 2020-01-09 18-10-23](https://user-images.githubusercontent.com/4522213/72120001-50b64200-330b-11ea-8533-4242b569d2cd.png)

@redshiftzero edit: This is an intermittent issue

Related but not the same as: https://github.com/freedomofpress/securedrop-client/issues/684

**Comment by ntoll** [comment]
Hmm.... I cannot reproduce this. Here's what I see when I use Ctrl+Enter:

![sd_ctrl_enter](https://user-images.githubusercontent.com/37602/72453285-bfd1e180-37b6-11ea-8c09-1c6cceb03e43.gif)

What OS / version of Qt5 are you using?

**Comment by rmol** [comment]
I was able to reproduce this on Debian. It worked on my first reply -- the placeholder text was cleared -- but after my second reply the text remained as I typed over it. It looks like it depends on whether you attempt the next reply during the conversation refresh. It can eventually correct.

**Comment by creviera** [comment]
Also confirmed it's happening in Qubes with python-pyqt5 version 5.11.3+dfsg-1+b3

**Comment by ntoll** [comment]
OK... so I thought I had Qubes / sd-workstation set up so I could follow the STR, but then something updated and I've just spent the past 2 hours trying to fix / wait for things to update (have been fixing minor things in meantime). And now Qubes is broken - complains of sys-usb doesn't exist. I admit I've been trying all sorts of commands so I've probably shot myself in the foot. :-( I might try a fresh install of Debian to try to reproduce. Very frustrating. :-/

**Comment by redshiftzero** [comment]
So I was able to reproduce this on master just now:

![Screen Shot 2020-01-16 at 11 14 03 AM](https://user-images.githubusercontent.com/7832803/72541986-6a96de00-3851-11ea-813d-b6664cc6b3fd.png)

Heads up that this was not on Qubes and not using Ctrl+enter to send, I've updated the STR as such. As @rmol suggests, it looks to be an intermittent issue, so it's probably due to the conversation view refreshing after reply success. As such, I expect it will probably go away once #660 and #473 are addressed. Let's deprioritize this one for now and then come back if it's still around when #660 and #473 are closed.

**Comment by ntoll** [comment]
@redshiftzero hah... you've caught me mid-installation of Debian onto a spare HD. Ack on the de-prioritization given those other tickets / issues being addressed soon. Will still try to reproduce though... ;-)

**Comment by ntoll** [comment]
OK... I've managed to reliably reproduce this behaviour while testing #688. I've fixed the issue in that branch and closed my initial PR (containing guesswork since I couldn't reproduce the problem) #712.

It turns out that the focus of the text_edit widget was the problem. If I shutdown my securedrop instance and then sent a message, then the DraftReply would fail and focus wouldn't switch to the messages (it remained in the text_edit widget). Ergo, while the placeholder was visible, since you **still** had focus in the text_edit you could type over the placeholder. The placeholder text was only removed when the text_edit gained focus. The solution was simply to take focus away from text_edit when send_reply in called.

**Comment by creviera** [comment]
related bug: https://github.com/freedomofpress/securedrop-client/issues/726
