### ISSUE TITLE
snippets don't update when content of message/reply is updated

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#707]
## STR

0. Submit a document so that there is a fresh submission to download in the next step.
1. Login to the client.
2. See the snippet displays our placeholder message.

## Expected behavior

As the message downloads, the content updates in the sidebar also.

## Actual behavior

The content is static, and will only refresh after a full sync (which will call the controller's `update_sources` method to update the sidebar). 

![Screen Shot 2020-01-17 at 8 42 12 PM](https://user-images.githubusercontent.com/7832803/72656530-f308a200-3969-11ea-9462-689988b5b48d.png)

## Comments

We do emit a signal each time a file, message, or reply is "ready" (i.e. has been successfully downloaded and decrypted), those signals are [here](https://github.com/freedomofpress/securedrop-client/blob/master/securedrop_client/logic.py#L131), so we could use make use of them in the source list view to update the source list view elements when the content is updated.

**Comment by eloquence** [comment]
Here's a pathological case:
![Screenshot_2020-01-17_17-24-33](https://user-images.githubusercontent.com/213636/72656684-e24c3200-3951-11ea-824f-37f130d5c824.png)

This is after login into a workstation that's not been initialized yet, with ~20 sources on the server. The preview snippets lag behind the actual retrieval and decryption of messages by a couple of minutes, i.e. I don't see previews for sources that do have content. Eventually they all display previews.

**Comment by redshiftzero** [comment]
they eventually display previews after a full sync has occurred, which is why it takes a couple of mins

**Comment by creviera** [comment]
I was able to repro in the case where there is are new messages from *new* sources

**Comment by creviera** [comment]
The fix for this issue should also work when applied to https://github.com/freedomofpress/securedrop-client/issues/442, fyi

**Comment by ntoll** [comment]
OK... I'm on this.

**Comment by ntoll** [comment]
Actually, parking this for moment to fix #715.

**Comment by ntoll** [comment]
OK... this probably relates to some of the issues described in the update made in #733.

**Comment by ntoll** [comment]
So I've been looking into this issue this afternoon. I'll push a branch/draft PR after stand-up (except it doesn't work).

I'm a bit stumped.

I can see messages, replies and files being downloaded, but in `on_message_download_success` (and related methods) the message doesn't actually have any content. When my slot catches the signal emitted by this method the same is still the case when I try to render the message as a snippet. Ergo, you just see the placeholder text instead of the content.

I've been tracing how this all fits together and, as far as I can tell, the database has been written to with the message content by the time methods like `storage.get_message` are called and the subsequent signal is fired. My expectation is that I'd get the latest copy of the message with the downloaded content when in the slot handling the signal. But `None` is returned as the content instead.

It's the end of the afternoon for me and I have tired eyes. I'll pick this up in the morning again and any pointers would be welcome. I've started looking at SqlAlchemy sessions and how one on one thread might update the database, but another (on the main thread) won't see the changes until... well, I'm speculating from the observed behaviour and need to investigate what perhaps needs to happen so a fresh SELECT is issued or a cache somewhere is cleared.

**Comment by ntoll** [comment]
WiP (sitting on top of inline-conversation) is in my `update-snippets` branch (https://github.com/ntoll/securedrop-client/tree/update-snippets). It should be easy, but see above comment about debugging fun.
