### ISSUE TITLE
Deletion in client and re-submission from same source results in error

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#717]
## STR
1. delete a source from the client
2. submit another document as that source 
3. click refresh and select the same source

## Expected
We should be able to see the new document from the source that was deleted earlier.

## Actual
```
Traceback (most recent call last):
  File "/home/creviera/workspace/freedomofpress/securedrop-client/securedrop_client/gui/widgets.py", line 748, in on_source_changed
    conversation_wrapper.conversation_view.update_conversation(source.collection)
  File "/home/creviera/workspace/freedomofpress/securedrop-client/securedrop_client/gui/widgets.py", line 2611, in update_conversation
    self.clear_conversation()
  File "/home/creviera/workspace/freedomofpress/securedrop-client/securedrop_client/gui/widgets.py", line 2604, in clear_conversation
    while self.conversation_layout.count():
RuntimeError: wrapped C/C++ object of type QVBoxLayout has been deleted
```

**Comment by eloquence** [comment]
If I perform the following operations in SecureDrop core (not the workstation)
1. submit as a new source, stay on submit screen
2. delete that source in the Journalist Interface
3. send another message

I get bounced to the index page. That is kind of what I'd expect, as deleting a source deletes all records/keys associated with them and prevents them from logging in. 

Is it possible that the refresh completes before the delete action lands on the server? If so, I think the expected behavior here would be to not re-create a source if its deletion is pending on the server.

**Comment by ntoll** [comment]
I've just had a look into this again. I cannot reproduce. Here's what I see:

* Submit a new source and stay on the submit screen.
* Wait for the new source to appear in the client. Delete source on client (the source disappears from the UI).
* Back at the source website, if I try to send a new message I get kicked out of the app.
* If I try to log in again with the code phrase I see  a message saying I'm not recognised.

Ergo, the "deleted source" crash in the client never presents itself. I guess this is fixed..? (Or, [likely] I'm missing something here).

**Comment by redshiftzero** [comment]
I think the problem here is the following race:

0. New source submits message A. 
1. Sync occurs in client. Journalist sees message A.
2. Source submits message B.
3. Journalist simultaneously deletes the source while the sync begins. Deletion completes as it occurs independently of the sync, but by this time the sync has collected the list of new messages, which includes message B.
4. Source is gone, yet the logic in the sync will attempt to add message B which corresponds to a source that is deleted.

Solution: we ensure that we discard messages, files, submissions corresponding to sources that have been deleted

**Comment by ntoll** [comment]
:+1: OK... I bagsy this for tomorrow's work. :-)

**Comment by creviera** [comment]
This issue has been resolved sometime between 21 days ago and now

**Comment by redshiftzero** [comment]
I think the race described above can still occur though, even if we can't reproduce it

**Comment by creviera** [comment]
ah i closed it because i was only checking the issue description STR, we should reopen, or better i'll create an issue for possible race conditions in the client since there are probably more

**Comment by rmol** [comment]
We did create #797 for the wider search for races, but I'm reopening this to capture the fix for the original issue.
