### ISSUE TITLE
Consider allowing for local deletion of downloaded submissions

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-client#742]
[needs investigation/discussion]

It might be a good idea to allow for the local deletion of submissions (stretch goal: or ephemeral/expiring downloads?) on the workstation locally, in the event that some submissions are deemed inappropriate for being accessible in offline mode, or being available on the machine.

Conceptually related: #552, multi-user support, per-journalist permission scope

**Comment by ninavizz** [comment]
Thx for filing this, Ro! Agreed, we definitely want to do this eventually.

I'd like to consider much bigger-picture, a way to track broader product-strategy level things like this, separate from GH Issues... namely, because GH Issues are primarily a place to track dev things, not so much longer-term product features/capabilities planning. It concerns me that important strategic thinking such as this will get lost in GitHub Issues. 

@eloquence I know we do not currently have a Product Manager resource or role established, but I feel it would buy the team some sanity if we could begin to think about how to better bucket/organize product strategy/planning stuff outside of GitHub, but intuitively findable and central enough to have meaning for the rest of the team?

**Comment by eloquence** [comment]
For starters, I'd recommend we capture this case in the [client user stories](https://docs.google.com/spreadsheets/d/1DQEQp-0e6zN-pCPa0qqY-MGtmpc2SN5mzUsR4nEkpCQ/edit#gid=0) spreadsheet, and use that as a starting point for longer-range planning and prioritization.

I think the simplest version of this is a "Delete only on this computer" checkbox which effectively implements a local lock against re-downloading a source. Worth emphasizing that anyone with the creds would still be able to re-download, but it would provide some mitigation as long as SecureDrop creds (at least the 2FA seed) are not stored on the same device, and I do think it could have value especially for distributed teams.

**Comment by zenmonkeykstop** [comment]
Closing in favour of freedomofpress/securedrop-workstation#914 as this is a larger-scope issue given the need for secure deletion.
