### ISSUE TITLE
Client crashed when I clicked the close button

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop-client#812]
## Steps I did

- [ ] The client loaded 1000 sources from a local container dev environment
- [ ] The UI was working fine.
- [ ] I clicked the close window button. And that caused the following error message

```
$ ./run.sh 
Running app with home directory: /tmp/tmp.N4cAO3i7Af

Current OS is *not* Qubes, disabling DispVM support...
gpg: keybox '/tmp/tmp.N4cAO3i7Af/gpg/pubring.kbx' created
gpg: /tmp/tmp.N4cAO3i7Af/gpg/trustdb.gpg: trustdb created
gpg: key CC40EF1228271441: public key "SecureDrop Test/Development (DO NOT USE IN PRODUCTION)" imported
gpg: key CC40EF1228271441: secret key imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret keys read: 1
gpg:   secret keys imported: 1
QWidget::setTabOrder: 'first' and 'second' must be in the same window
QWidget::setTabOrder: 'first' and 'second' must be in the same window
QWidget::setTabOrder: 'first' and 'second' must be in the same window
QWidget::setTabOrder: 'first' and 'second' must be in the same window
QWidget::setTabOrder: 'first' and 'second' must be in the same window
QWidget::setTabOrder: 'first' and 'second' must be in the same window
QWidget::setTabOrder: 'first' and 'second' must be in the same window
QWidget::setTabOrder: 'first' and 'second' must be in the same window
QWidget::setTabOrder: 'first' and 'second' must be in the same window
QWidget::setTabOrder: 'first' and 'second' must be in the same window
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.


(python:15388): GLib-CRITICAL **: 16:22:21.538: g_source_unref_internal: assertion 'source != NULL' failed

``` 

I am yet to search anything on the error. I just copy-pasted the error message here.

**Comment by ntoll** [comment]
I've (finally) managed to reproduce this as per Kushal's instructions. This error message is intermittent too (mostly I don't see it, sometimes I do).

The questions now is do we want to do anything about it, since the behaviour of the crash is simply that the application closes (which is the intention behind clicking the close window button). Upon restart the data is all there and the download of missing messages resumes.

One thing I did notice is that there's a "black out" of drawing the UI upon start as the local sources and related messages are loaded (see screenie below):

![blocked_startup](https://user-images.githubusercontent.com/37602/75795529-5e67d100-5d6a-11ea-8f48-a904833df6e6.gif)

**Comment by ntoll** [comment]
@redshiftzero @creviera @eloquence I think this can be closed now.

**Comment by kushaldas** [comment]
The blackout is happening most probably due to too many widgets loading.

**Comment by ntoll** [comment]
@kushaldas the blackout has been fixed. ;-)

**Comment by kushaldas** [comment]
Closing this one.
