### ISSUE TITLE
enter closes export and print dialog

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-client#828]
# STR

1. press enter at any point in the dialog

# Expected 

For the continue button to be pressed by default, if cancel button is selected for that to be pressed

# Actual

The dialog closes

**Comment by ntoll** [comment]
I've just been looking into this in some depth. Perhaps I'm missing something here, but I'm not really sure what's going on since the expected behaviour is that the button with focus responds to a "click" event (which can be triggered by pressing the "Enter" key).

No end of fiddling around, tracking events and walking through the code has allowed me to make it work in the "expected" way. :-/

However, we *could* set each button with a keyboard shortcut (enter for accept, escape for cancel). But this isn't exactly what you asked for even though it'd be a relatively easy thing to implement. The blocker is working out exactly what the behaviour should be, given that the expected behaviour isn't what's happening.

Thoughts..?

**Comment by creviera** [comment]
> I've just been looking into this in some depth. Perhaps I'm missing something here, but I'm not really sure what's going on since the expected behaviour is that the button with focus responds to a "click" event (which can be triggered by pressing the "Enter" key).

Since the dialog sets the `Popup` window flag (we do this in order to not see a window frame header in Qubes since setting the `FramelessWindowHint` is ignored by Qubes' window manager), the dialog inherits the default behavior of a popup to close when a user presses the Enter key. The desired behavior is for the dialog to remain open and for Enter to "click" the selected button (by default it's the "Continue" button).

**Comment by creviera** [comment]
> However, we could set each button with a keyboard shortcut (enter for accept, escape for cancel). But this isn't exactly what you asked for even though it'd be a relatively easy thing to implement. The blocker is working out exactly what the behaviour should be, given that the expected behaviour isn't what's happening.

I think in general we should rely on Qt defaults, because generally they're good. It's just because of this FramelessWindowHint-not-working-in-Qubes workaround that we have to hack it together.
