### ISSUE TITLE
Source widget tooltip weirdness

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#999]
## Description
When my mouse hits the exact pixels of a character in the preview text on a Source, the preview text appears as a tooltip. 

## STR
Hover the arrow over the exact pixels of a character on a Source's preview text. I can always reproduce this on the top-most source in the list, but have had a harder time getting it to reproduce with other sources; regardless of their selection status.

## Expected
Either no tooltip at all, or a tooltip for the whole individual source widget that simply says "source" or the source's codename. My preference would be for the prior, as that's the most useful information for a screenreader—which is the standard UX pattern for tooltips (what the object is).

## Actual
The content of the source widget's preview text.

**Comment by eloquence** [comment]
I believe this may be a side effect of the tooltips added for long filenames in #840. They will show for previews that are elided (with "...") due to length. The tooltips will take up an extreme width if the original text was a long paragraph without linebreaks:

![megatip](https://user-images.githubusercontent.com/213636/77506628-a1363980-6e3c-11ea-81d9-214afd8c741d.png)

I think the correct behavior here is to suppress the tooltips for previews. Previews are only intended to give a suggestion of the last interaction with the source, we don't need the additional complexity of tooltips on the previews.

**Comment by eloquence** [comment]
Due to the severity of the pathological tooltip case above I've removed the "low priority" label.
